// Code generated by MockGen. DO NOT EDIT.
// Source: I:\Goland\keeper\internal\server\domain\uow.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/DimKa163/keeper/internal/server/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockUnitOfWork is a mock of UnitOfWork interface.
type MockUnitOfWork struct {
	ctrl     *gomock.Controller
	recorder *MockUnitOfWorkMockRecorder
}

// MockUnitOfWorkMockRecorder is the mock recorder for MockUnitOfWork.
type MockUnitOfWorkMockRecorder struct {
	mock *MockUnitOfWork
}

// NewMockUnitOfWork creates a new mock instance.
func NewMockUnitOfWork(ctrl *gomock.Controller) *MockUnitOfWork {
	mock := &MockUnitOfWork{ctrl: ctrl}
	mock.recorder = &MockUnitOfWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnitOfWork) EXPECT() *MockUnitOfWorkMockRecorder {
	return m.recorder
}

// SecretRepository mocks base method.
func (m *MockUnitOfWork) SecretRepository() domain.SecretRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SecretRepository")
	ret0, _ := ret[0].(domain.SecretRepository)
	return ret0
}

// SecretRepository indicates an expected call of SecretRepository.
func (mr *MockUnitOfWorkMockRecorder) SecretRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SecretRepository", reflect.TypeOf((*MockUnitOfWork)(nil).SecretRepository))
}

// SyncStateRepository mocks base method.
func (m *MockUnitOfWork) SyncStateRepository() domain.SyncStateRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncStateRepository")
	ret0, _ := ret[0].(domain.SyncStateRepository)
	return ret0
}

// SyncStateRepository indicates an expected call of SyncStateRepository.
func (mr *MockUnitOfWorkMockRecorder) SyncStateRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncStateRepository", reflect.TypeOf((*MockUnitOfWork)(nil).SyncStateRepository))
}

// Tx mocks base method.
func (m *MockUnitOfWork) Tx(ctx context.Context, fn func(context.Context, domain.UnitOfWork) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Tx indicates an expected call of Tx.
func (mr *MockUnitOfWorkMockRecorder) Tx(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tx", reflect.TypeOf((*MockUnitOfWork)(nil).Tx), ctx, fn)
}

// UserRepository mocks base method.
func (m *MockUnitOfWork) UserRepository() domain.UserRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserRepository")
	ret0, _ := ret[0].(domain.UserRepository)
	return ret0
}

// UserRepository indicates an expected call of UserRepository.
func (mr *MockUnitOfWorkMockRecorder) UserRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserRepository", reflect.TypeOf((*MockUnitOfWork)(nil).UserRepository))
}
