// Code generated by MockGen. DO NOT EDIT.
// Source: I:\Goland\keeper\internal\server\domain\data.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/DimKa163/keeper/internal/server/domain"
	guid "github.com/beevik/guid"
	gomock "github.com/golang/mock/gomock"
)

// MockStoredDataRepository is a mock of StoredDataRepository interface.
type MockStoredDataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStoredDataRepositoryMockRecorder
}

// MockStoredDataRepositoryMockRecorder is the mock recorder for MockStoredDataRepository.
type MockStoredDataRepositoryMockRecorder struct {
	mock *MockStoredDataRepository
}

// NewMockStoredDataRepository creates a new mock instance.
func NewMockStoredDataRepository(ctrl *gomock.Controller) *MockStoredDataRepository {
	mock := &MockStoredDataRepository{ctrl: ctrl}
	mock.recorder = &MockStoredDataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoredDataRepository) EXPECT() *MockStoredDataRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockStoredDataRepository) Delete(ctx context.Context, id guid.Guid) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStoredDataRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStoredDataRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockStoredDataRepository) Get(ctx context.Context, id guid.Guid) (*domain.StoredData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.StoredData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStoredDataRepositoryMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStoredDataRepository)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockStoredDataRepository) GetAll(ctx context.Context, userID guid.Guid, limit, skip int) ([]*domain.StoredData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, userID, limit, skip)
	ret0, _ := ret[0].([]*domain.StoredData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockStoredDataRepositoryMockRecorder) GetAll(ctx, userID, limit, skip interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockStoredDataRepository)(nil).GetAll), ctx, userID, limit, skip)
}

// Insert mocks base method.
func (m *MockStoredDataRepository) Insert(ctx context.Context, data *domain.StoredData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockStoredDataRepositoryMockRecorder) Insert(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockStoredDataRepository)(nil).Insert), ctx, data)
}

// Update mocks base method.
func (m *MockStoredDataRepository) Update(ctx context.Context, data *domain.StoredData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStoredDataRepositoryMockRecorder) Update(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStoredDataRepository)(nil).Update), ctx, data)
}

// MockFilePartRepository is a mock of FilePartRepository interface.
type MockFilePartRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFilePartRepositoryMockRecorder
}

// MockFilePartRepositoryMockRecorder is the mock recorder for MockFilePartRepository.
type MockFilePartRepositoryMockRecorder struct {
	mock *MockFilePartRepository
}

// NewMockFilePartRepository creates a new mock instance.
func NewMockFilePartRepository(ctrl *gomock.Controller) *MockFilePartRepository {
	mock := &MockFilePartRepository{ctrl: ctrl}
	mock.recorder = &MockFilePartRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilePartRepository) EXPECT() *MockFilePartRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockFilePartRepository) Get(ctx context.Context, dataID int64) ([]*domain.FilePart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, dataID)
	ret0, _ := ret[0].([]*domain.FilePart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFilePartRepositoryMockRecorder) Get(ctx, dataID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFilePartRepository)(nil).Get), ctx, dataID)
}

// MockIDataProvider is a mock of IDataProvider interface.
type MockIDataProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIDataProviderMockRecorder
}

// MockIDataProviderMockRecorder is the mock recorder for MockIDataProvider.
type MockIDataProviderMockRecorder struct {
	mock *MockIDataProvider
}

// NewMockIDataProvider creates a new mock instance.
func NewMockIDataProvider(ctrl *gomock.Controller) *MockIDataProvider {
	mock := &MockIDataProvider{ctrl: ctrl}
	mock.recorder = &MockIDataProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDataProvider) EXPECT() *MockIDataProviderMockRecorder {
	return m.recorder
}

// ExecuteReader mocks base method.
func (m *MockIDataProvider) ExecuteReader(ctx context.Context, dataID guid.Guid) domain.Reader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteReader", ctx, dataID)
	ret0, _ := ret[0].(domain.Reader)
	return ret0
}

// ExecuteReader indicates an expected call of ExecuteReader.
func (mr *MockIDataProviderMockRecorder) ExecuteReader(ctx, dataID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteReader", reflect.TypeOf((*MockIDataProvider)(nil).ExecuteReader), ctx, dataID)
}

// ExecuteWriter mocks base method.
func (m *MockIDataProvider) ExecuteWriter(ctx context.Context, dataID guid.Guid) domain.Writer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteWriter", ctx, dataID)
	ret0, _ := ret[0].(domain.Writer)
	return ret0
}

// ExecuteWriter indicates an expected call of ExecuteWriter.
func (mr *MockIDataProviderMockRecorder) ExecuteWriter(ctx, dataID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteWriter", reflect.TypeOf((*MockIDataProvider)(nil).ExecuteWriter), ctx, dataID)
}

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockWriter) Write(ctx context.Context, part *domain.FilePart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", ctx, part)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockWriterMockRecorder) Write(ctx, part interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockWriter)(nil).Write), ctx, part)
}

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockReader) Read(ctx context.Context) (*domain.FilePart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx)
	ret0, _ := ret[0].(*domain.FilePart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockReaderMockRecorder) Read(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockReader)(nil).Read), ctx)
}
