// Code generated by MockGen. DO NOT EDIT.
// Source: I:\Goland\keeper\internal\server\domain\sync_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/DimKa163/keeper/internal/server/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockSyncStateRepository is a mock of SyncStateRepository interface.
type MockSyncStateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSyncStateRepositoryMockRecorder
}

// MockSyncStateRepositoryMockRecorder is the mock recorder for MockSyncStateRepository.
type MockSyncStateRepositoryMockRecorder struct {
	mock *MockSyncStateRepository
}

// NewMockSyncStateRepository creates a new mock instance.
func NewMockSyncStateRepository(ctrl *gomock.Controller) *MockSyncStateRepository {
	mock := &MockSyncStateRepository{ctrl: ctrl}
	mock.recorder = &MockSyncStateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncStateRepository) EXPECT() *MockSyncStateRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSyncStateRepository) Get(ctx context.Context, id string) (*domain.SyncState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.SyncState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSyncStateRepositoryMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSyncStateRepository)(nil).Get), ctx, id)
}

// Save mocks base method.
func (m *MockSyncStateRepository) Save(ctx context.Context, syncState *domain.SyncState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, syncState)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSyncStateRepositoryMockRecorder) Save(ctx, syncState interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSyncStateRepository)(nil).Save), ctx, syncState)
}
