// Code generated by MockGen. DO NOT EDIT.
// Source: I:\Goland\keeper\internal\server\domain\data.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/DimKa163/keeper/internal/server/domain"
	guid "github.com/beevik/guid"
	gomock "github.com/golang/mock/gomock"
)

// MockDataRepository is a mock of DataRepository interface.
type MockDataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDataRepositoryMockRecorder
}

// MockDataRepositoryMockRecorder is the mock recorder for MockDataRepository.
type MockDataRepositoryMockRecorder struct {
	mock *MockDataRepository
}

// NewMockDataRepository creates a new mock instance.
func NewMockDataRepository(ctrl *gomock.Controller) *MockDataRepository {
	mock := &MockDataRepository{ctrl: ctrl}
	mock.recorder = &MockDataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataRepository) EXPECT() *MockDataRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDataRepository) Delete(ctx context.Context, id guid.Guid) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockDataRepository) Get(ctx context.Context, id guid.Guid) (*domain.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDataRepositoryMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDataRepository)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockDataRepository) GetAll(ctx context.Context, userID guid.Guid, limit, skip int) ([]*domain.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, userID, limit, skip)
	ret0, _ := ret[0].([]*domain.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDataRepositoryMockRecorder) GetAll(ctx, userID, limit, skip interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDataRepository)(nil).GetAll), ctx, userID, limit, skip)
}

// Insert mocks base method.
func (m *MockDataRepository) Insert(ctx context.Context, data *domain.Data) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockDataRepositoryMockRecorder) Insert(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockDataRepository)(nil).Insert), ctx, data)
}

// Update mocks base method.
func (m *MockDataRepository) Update(ctx context.Context, data *domain.Data) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataRepositoryMockRecorder) Update(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataRepository)(nil).Update), ctx, data)
}

// MockFilePartRepository is a mock of FilePartRepository interface.
type MockFilePartRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFilePartRepositoryMockRecorder
}

// MockFilePartRepositoryMockRecorder is the mock recorder for MockFilePartRepository.
type MockFilePartRepositoryMockRecorder struct {
	mock *MockFilePartRepository
}

// NewMockFilePartRepository creates a new mock instance.
func NewMockFilePartRepository(ctrl *gomock.Controller) *MockFilePartRepository {
	mock := &MockFilePartRepository{ctrl: ctrl}
	mock.recorder = &MockFilePartRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilePartRepository) EXPECT() *MockFilePartRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockFilePartRepository) Get(ctx context.Context, dataID int64) ([]*domain.FilePart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, dataID)
	ret0, _ := ret[0].([]*domain.FilePart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFilePartRepositoryMockRecorder) Get(ctx, dataID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFilePartRepository)(nil).Get), ctx, dataID)
}

// MockDataService is a mock of DataService interface.
type MockDataService struct {
	ctrl     *gomock.Controller
	recorder *MockDataServiceMockRecorder
}

// MockDataServiceMockRecorder is the mock recorder for MockDataService.
type MockDataServiceMockRecorder struct {
	mock *MockDataService
}

// NewMockDataService creates a new mock instance.
func NewMockDataService(ctrl *gomock.Controller) *MockDataService {
	mock := &MockDataService{ctrl: ctrl}
	mock.recorder = &MockDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataService) EXPECT() *MockDataServiceMockRecorder {
	return m.recorder
}

// GetIterator mocks base method.
func (m *MockDataService) GetIterator() domain.DataIterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIterator")
	ret0, _ := ret[0].(domain.DataIterator)
	return ret0
}

// GetIterator indicates an expected call of GetIterator.
func (mr *MockDataServiceMockRecorder) GetIterator() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIterator", reflect.TypeOf((*MockDataService)(nil).GetIterator))
}

// Push mocks base method.
func (m *MockDataService) Push(ctx context.Context, data []*domain.Operation) ([]domain.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", ctx, data)
	ret0, _ := ret[0].([]domain.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Push indicates an expected call of Push.
func (mr *MockDataServiceMockRecorder) Push(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockDataService)(nil).Push), ctx, data)
}

// MockDataIterator is a mock of DataIterator interface.
type MockDataIterator struct {
	ctrl     *gomock.Controller
	recorder *MockDataIteratorMockRecorder
}

// MockDataIteratorMockRecorder is the mock recorder for MockDataIterator.
type MockDataIteratorMockRecorder struct {
	mock *MockDataIterator
}

// NewMockDataIterator creates a new mock instance.
func NewMockDataIterator(ctrl *gomock.Controller) *MockDataIterator {
	mock := &MockDataIterator{ctrl: ctrl}
	mock.recorder = &MockDataIteratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataIterator) EXPECT() *MockDataIteratorMockRecorder {
	return m.recorder
}

// Current mocks base method.
func (m *MockDataIterator) Current() *domain.Data {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current")
	ret0, _ := ret[0].(*domain.Data)
	return ret0
}

// Current indicates an expected call of Current.
func (mr *MockDataIteratorMockRecorder) Current() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockDataIterator)(nil).Current))
}

// MoveNext mocks base method.
func (m *MockDataIterator) MoveNext(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveNext", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveNext indicates an expected call of MoveNext.
func (mr *MockDataIteratorMockRecorder) MoveNext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveNext", reflect.TypeOf((*MockDataIterator)(nil).MoveNext), ctx)
}
