// Code generated by MockGen. DO NOT EDIT.
// Source: I:\Goland\keeper\internal\server\domain\filer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFiler is a mock of Filer interface.
type MockFiler struct {
	ctrl     *gomock.Controller
	recorder *MockFilerMockRecorder
}

// MockFilerMockRecorder is the mock recorder for MockFiler.
type MockFilerMockRecorder struct {
	mock *MockFiler
}

// NewMockFiler creates a new mock instance.
func NewMockFiler(ctrl *gomock.Controller) *MockFiler {
	mock := &MockFiler{ctrl: ctrl}
	mock.recorder = &MockFilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFiler) EXPECT() *MockFilerMockRecorder {
	return m.recorder
}

// OpenRead mocks base method.
func (m *MockFiler) OpenRead(fileName string, version int32, dst ...string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{fileName, version}
	for _, a := range dst {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "OpenRead", varargs...)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenRead indicates an expected call of OpenRead.
func (mr *MockFilerMockRecorder) OpenRead(fileName, version interface{}, dst ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{fileName, version}, dst...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenRead", reflect.TypeOf((*MockFiler)(nil).OpenRead), varargs...)
}

// OpenWrite mocks base method.
func (m *MockFiler) OpenWrite(fileName string, version int32, dst ...string) (io.WriteCloser, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{fileName, version}
	for _, a := range dst {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "OpenWrite", varargs...)
	ret0, _ := ret[0].(io.WriteCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenWrite indicates an expected call of OpenWrite.
func (mr *MockFilerMockRecorder) OpenWrite(fileName, version interface{}, dst ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{fileName, version}, dst...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenWrite", reflect.TypeOf((*MockFiler)(nil).OpenWrite), varargs...)
}

// Remove mocks base method.
func (m *MockFiler) Remove(fileName string, version int32, dst ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{fileName, version}
	for _, a := range dst {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Remove", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockFilerMockRecorder) Remove(fileName, version interface{}, dst ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{fileName, version}, dst...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockFiler)(nil).Remove), varargs...)
}
