// Code generated by MockGen. DO NOT EDIT.
// Source: I:\Goland\keeper\internal\pb\data_grpc.pb.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pb "github.com/DimKa163/keeper/internal/pb"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockSyncDataClient is a mock of SyncDataClient interface.
type MockSyncDataClient struct {
	ctrl     *gomock.Controller
	recorder *MockSyncDataClientMockRecorder
}

// MockSyncDataClientMockRecorder is the mock recorder for MockSyncDataClient.
type MockSyncDataClientMockRecorder struct {
	mock *MockSyncDataClient
}

// NewMockSyncDataClient creates a new mock instance.
func NewMockSyncDataClient(ctrl *gomock.Controller) *MockSyncDataClient {
	mock := &MockSyncDataClient{ctrl: ctrl}
	mock.recorder = &MockSyncDataClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncDataClient) EXPECT() *MockSyncDataClientMockRecorder {
	return m.recorder
}

// Poll mocks base method.
func (m *MockSyncDataClient) Poll(ctx context.Context, in *pb.PollRequest, opts ...grpc.CallOption) (*pb.PollResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Poll", varargs...)
	ret0, _ := ret[0].(*pb.PollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Poll indicates an expected call of Poll.
func (mr *MockSyncDataClientMockRecorder) Poll(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Poll", reflect.TypeOf((*MockSyncDataClient)(nil).Poll), varargs...)
}

// Push mocks base method.
func (m *MockSyncDataClient) Push(ctx context.Context, in *pb.PushRequest, opts ...grpc.CallOption) (*pb.PushResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Push", varargs...)
	ret0, _ := ret[0].(*pb.PushResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Push indicates an expected call of Push.
func (mr *MockSyncDataClientMockRecorder) Push(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockSyncDataClient)(nil).Push), varargs...)
}

// MockSyncDataServer is a mock of SyncDataServer interface.
type MockSyncDataServer struct {
	ctrl     *gomock.Controller
	recorder *MockSyncDataServerMockRecorder
}

// MockSyncDataServerMockRecorder is the mock recorder for MockSyncDataServer.
type MockSyncDataServerMockRecorder struct {
	mock *MockSyncDataServer
}

// NewMockSyncDataServer creates a new mock instance.
func NewMockSyncDataServer(ctrl *gomock.Controller) *MockSyncDataServer {
	mock := &MockSyncDataServer{ctrl: ctrl}
	mock.recorder = &MockSyncDataServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncDataServer) EXPECT() *MockSyncDataServerMockRecorder {
	return m.recorder
}

// Poll mocks base method.
func (m *MockSyncDataServer) Poll(arg0 context.Context, arg1 *pb.PollRequest) (*pb.PollResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Poll", arg0, arg1)
	ret0, _ := ret[0].(*pb.PollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Poll indicates an expected call of Poll.
func (mr *MockSyncDataServerMockRecorder) Poll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Poll", reflect.TypeOf((*MockSyncDataServer)(nil).Poll), arg0, arg1)
}

// Push mocks base method.
func (m *MockSyncDataServer) Push(arg0 context.Context, arg1 *pb.PushRequest) (*pb.PushResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", arg0, arg1)
	ret0, _ := ret[0].(*pb.PushResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Push indicates an expected call of Push.
func (mr *MockSyncDataServerMockRecorder) Push(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockSyncDataServer)(nil).Push), arg0, arg1)
}

// mustEmbedUnimplementedSyncDataServer mocks base method.
func (m *MockSyncDataServer) mustEmbedUnimplementedSyncDataServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedSyncDataServer")
}

// mustEmbedUnimplementedSyncDataServer indicates an expected call of mustEmbedUnimplementedSyncDataServer.
func (mr *MockSyncDataServerMockRecorder) mustEmbedUnimplementedSyncDataServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedSyncDataServer", reflect.TypeOf((*MockSyncDataServer)(nil).mustEmbedUnimplementedSyncDataServer))
}

// MockUnsafeSyncDataServer is a mock of UnsafeSyncDataServer interface.
type MockUnsafeSyncDataServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeSyncDataServerMockRecorder
}

// MockUnsafeSyncDataServerMockRecorder is the mock recorder for MockUnsafeSyncDataServer.
type MockUnsafeSyncDataServerMockRecorder struct {
	mock *MockUnsafeSyncDataServer
}

// NewMockUnsafeSyncDataServer creates a new mock instance.
func NewMockUnsafeSyncDataServer(ctrl *gomock.Controller) *MockUnsafeSyncDataServer {
	mock := &MockUnsafeSyncDataServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeSyncDataServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeSyncDataServer) EXPECT() *MockUnsafeSyncDataServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedSyncDataServer mocks base method.
func (m *MockUnsafeSyncDataServer) mustEmbedUnimplementedSyncDataServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedSyncDataServer")
}

// mustEmbedUnimplementedSyncDataServer indicates an expected call of mustEmbedUnimplementedSyncDataServer.
func (mr *MockUnsafeSyncDataServerMockRecorder) mustEmbedUnimplementedSyncDataServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedSyncDataServer", reflect.TypeOf((*MockUnsafeSyncDataServer)(nil).mustEmbedUnimplementedSyncDataServer))
}
