// Code generated by MockGen. DO NOT EDIT.
// Source: I:\Goland\keeper\internal\server\domain\sync.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/DimKa163/keeper/internal/server/domain"
	guid "github.com/beevik/guid"
	gomock "github.com/golang/mock/gomock"
)

// MockSyncStateRepository is a mock of SyncStateRepository interface.
type MockSyncStateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSyncStateRepositoryMockRecorder
}

// MockSyncStateRepositoryMockRecorder is the mock recorder for MockSyncStateRepository.
type MockSyncStateRepositoryMockRecorder struct {
	mock *MockSyncStateRepository
}

// NewMockSyncStateRepository creates a new mock instance.
func NewMockSyncStateRepository(ctrl *gomock.Controller) *MockSyncStateRepository {
	mock := &MockSyncStateRepository{ctrl: ctrl}
	mock.recorder = &MockSyncStateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncStateRepository) EXPECT() *MockSyncStateRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSyncStateRepository) Get(ctx context.Context, id string, user guid.Guid) (*domain.SyncState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id, user)
	ret0, _ := ret[0].(*domain.SyncState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSyncStateRepositoryMockRecorder) Get(ctx, id, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSyncStateRepository)(nil).Get), ctx, id, user)
}

// Insert mocks base method.
func (m *MockSyncStateRepository) Insert(ctx context.Context, state *domain.SyncState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockSyncStateRepositoryMockRecorder) Insert(ctx, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockSyncStateRepository)(nil).Insert), ctx, state)
}

// Update mocks base method.
func (m *MockSyncStateRepository) Update(ctx context.Context, syncState *domain.SyncState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, syncState)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSyncStateRepositoryMockRecorder) Update(ctx, syncState interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSyncStateRepository)(nil).Update), ctx, syncState)
}
