// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: app/api/proto/data.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestType int32

const (
	RequestType_Default   RequestType = 0
	RequestType_StartData RequestType = 1
	RequestType_FilePart  RequestType = 2
	RequestType_EndData   RequestType = 3
	RequestType_ErrData   RequestType = 4
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "Default",
		1: "StartData",
		2: "FilePart",
		3: "EndData",
		4: "ErrData",
	}
	RequestType_value = map[string]int32{
		"Default":   0,
		"StartData": 1,
		"FilePart":  2,
		"EndData":   3,
		"ErrData":   4,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_api_proto_data_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_app_api_proto_data_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Data_DataType int32

const (
	Data_LoginPass Data_DataType = 0
	Data_Text      Data_DataType = 1
	Data_BankCard  Data_DataType = 2
	Data_Other     Data_DataType = 3
)

// Enum value maps for Data_DataType.
var (
	Data_DataType_name = map[int32]string{
		0: "LoginPass",
		1: "Text",
		2: "BankCard",
		3: "Other",
	}
	Data_DataType_value = map[string]int32{
		"LoginPass": 0,
		"Text":      1,
		"BankCard":  2,
		"Other":     3,
	}
)

func (x Data_DataType) Enum() *Data_DataType {
	p := new(Data_DataType)
	*p = x
	return p
}

func (x Data_DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Data_DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_api_proto_data_proto_enumTypes[1].Descriptor()
}

func (Data_DataType) Type() protoreflect.EnumType {
	return &file_app_api_proto_data_proto_enumTypes[1]
}

func (x Data_DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Data struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name          *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Type          Data_DataType          `protobuf:"varint,3,opt,name=type,enum=go.Data_DataType"`
	xxx_hidden_Large         bool                   `protobuf:"varint,4,opt,name=large"`
	xxx_hidden_DekNonce      []byte                 `protobuf:"bytes,5,opt,name=dek_nonce,json=dekNonce"`
	xxx_hidden_Dek           []byte                 `protobuf:"bytes,6,opt,name=dek"`
	xxx_hidden_DataNonce     []byte                 `protobuf:"bytes,7,opt,name=data_nonce,json=dataNonce"`
	xxx_hidden_Data          []byte                 `protobuf:"bytes,8,opt,name=data"`
	xxx_hidden_FileDataNonce []byte                 `protobuf:"bytes,9,opt,name=file_data_nonce,json=fileDataNonce"`
	xxx_hidden_Version       int32                  `protobuf:"varint,10,opt,name=version"`
	xxx_hidden_Deleted       bool                   `protobuf:"varint,11,opt,name=deleted"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_app_api_proto_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Data) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Data) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Data) GetType() Data_DataType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Type
		}
	}
	return Data_LoginPass
}

func (x *Data) GetLarge() bool {
	if x != nil {
		return x.xxx_hidden_Large
	}
	return false
}

func (x *Data) GetDekNonce() []byte {
	if x != nil {
		return x.xxx_hidden_DekNonce
	}
	return nil
}

func (x *Data) GetDek() []byte {
	if x != nil {
		return x.xxx_hidden_Dek
	}
	return nil
}

func (x *Data) GetDataNonce() []byte {
	if x != nil {
		return x.xxx_hidden_DataNonce
	}
	return nil
}

func (x *Data) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Data) GetFileDataNonce() []byte {
	if x != nil {
		return x.xxx_hidden_FileDataNonce
	}
	return nil
}

func (x *Data) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *Data) GetDeleted() bool {
	if x != nil {
		return x.xxx_hidden_Deleted
	}
	return false
}

func (x *Data) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 11)
}

func (x *Data) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 11)
}

func (x *Data) SetType(v Data_DataType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 11)
}

func (x *Data) SetLarge(v bool) {
	x.xxx_hidden_Large = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 11)
}

func (x *Data) SetDekNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_DekNonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 11)
}

func (x *Data) SetDek(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Dek = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 11)
}

func (x *Data) SetDataNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_DataNonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 11)
}

func (x *Data) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 11)
}

func (x *Data) SetFileDataNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_FileDataNonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 11)
}

func (x *Data) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 11)
}

func (x *Data) SetDeleted(v bool) {
	x.xxx_hidden_Deleted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 11)
}

func (x *Data) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Data) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Data) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Data) HasLarge() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Data) HasDekNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Data) HasDek() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Data) HasDataNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Data) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *Data) HasFileDataNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *Data) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *Data) HasDeleted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *Data) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Data) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *Data) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Type = Data_LoginPass
}

func (x *Data) ClearLarge() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Large = false
}

func (x *Data) ClearDekNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_DekNonce = nil
}

func (x *Data) ClearDek() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Dek = nil
}

func (x *Data) ClearDataNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_DataNonce = nil
}

func (x *Data) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Data = nil
}

func (x *Data) ClearFileDataNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_FileDataNonce = nil
}

func (x *Data) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Version = 0
}

func (x *Data) ClearDeleted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_Deleted = false
}

type Data_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id            *string
	Name          *string
	Type          *Data_DataType
	Large         *bool
	DekNonce      []byte
	Dek           []byte
	DataNonce     []byte
	Data          []byte
	FileDataNonce []byte
	Version       *int32
	Deleted       *bool
}

func (b0 Data_builder) Build() *Data {
	m0 := &Data{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 11)
		x.xxx_hidden_Id = b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 11)
		x.xxx_hidden_Name = b.Name
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 11)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Large != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 11)
		x.xxx_hidden_Large = *b.Large
	}
	if b.DekNonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 11)
		x.xxx_hidden_DekNonce = b.DekNonce
	}
	if b.Dek != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 11)
		x.xxx_hidden_Dek = b.Dek
	}
	if b.DataNonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 11)
		x.xxx_hidden_DataNonce = b.DataNonce
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 11)
		x.xxx_hidden_Data = b.Data
	}
	if b.FileDataNonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 11)
		x.xxx_hidden_FileDataNonce = b.FileDataNonce
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 11)
		x.xxx_hidden_Version = *b.Version
	}
	if b.Deleted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 11)
		x.xxx_hidden_Deleted = *b.Deleted
	}
	return m0
}

type PushRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data *[]*Data               `protobuf:"bytes,1,rep,name=data"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_app_api_proto_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PushRequest) GetData() []*Data {
	if x != nil {
		if x.xxx_hidden_Data != nil {
			return *x.xxx_hidden_Data
		}
	}
	return nil
}

func (x *PushRequest) SetData(v []*Data) {
	x.xxx_hidden_Data = &v
}

type PushRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data []*Data
}

func (b0 PushRequest_builder) Build() *PushRequest {
	m0 := &PushRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = &b.Data
	return m0
}

type Push struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data        *Data                  `protobuf:"bytes,1,opt,name=data"`
	xxx_hidden_Type        RequestType            `protobuf:"varint,2,opt,name=type,enum=go.RequestType"`
	xxx_hidden_Chunk       []byte                 `protobuf:"bytes,3,opt,name=chunk"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Push) Reset() {
	*x = Push{}
	mi := &file_app_api_proto_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Push) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Push) ProtoMessage() {}

func (x *Push) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Push) GetData() *Data {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Push) GetType() RequestType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Type
		}
	}
	return RequestType_Default
}

func (x *Push) GetChunk() []byte {
	if x != nil {
		return x.xxx_hidden_Chunk
	}
	return nil
}

func (x *Push) SetData(v *Data) {
	x.xxx_hidden_Data = v
}

func (x *Push) SetType(v RequestType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Push) SetChunk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Chunk = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Push) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *Push) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Push) HasChunk() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Push) ClearData() {
	x.xxx_hidden_Data = nil
}

func (x *Push) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = RequestType_Default
}

func (x *Push) ClearChunk() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Chunk = nil
}

type Push_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data  *Data
	Type  *RequestType
	Chunk []byte
}

func (b0 Push_builder) Build() *Push {
	m0 := &Push{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = b.Data
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Chunk != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Chunk = b.Chunk
	}
	return m0
}

type PushResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success     bool                   `protobuf:"varint,1,opt,name=success"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_app_api_proto_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PushResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *PushResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *PushResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PushResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Success = false
}

type PushResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success *bool
}

func (b0 PushResponse_builder) Build() *PushResponse {
	m0 := &PushResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Success = *b.Success
	}
	return m0
}

type PollRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Since       int32                  `protobuf:"varint,1,opt,name=since"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_app_api_proto_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PollRequest) GetSince() int32 {
	if x != nil {
		return x.xxx_hidden_Since
	}
	return 0
}

func (x *PollRequest) SetSince(v int32) {
	x.xxx_hidden_Since = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *PollRequest) HasSince() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PollRequest) ClearSince() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Since = 0
}

type PollRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Since *int32
}

func (b0 PollRequest_builder) Build() *PollRequest {
	m0 := &PollRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Since != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Since = *b.Since
	}
	return m0
}

type PollResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ServerVersion int32                  `protobuf:"varint,1,opt,name=server_version,json=serverVersion"`
	xxx_hidden_Data          *[]*Data               `protobuf:"bytes,2,rep,name=data"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_app_api_proto_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PollResponse) GetServerVersion() int32 {
	if x != nil {
		return x.xxx_hidden_ServerVersion
	}
	return 0
}

func (x *PollResponse) GetData() []*Data {
	if x != nil {
		if x.xxx_hidden_Data != nil {
			return *x.xxx_hidden_Data
		}
	}
	return nil
}

func (x *PollResponse) SetServerVersion(v int32) {
	x.xxx_hidden_ServerVersion = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *PollResponse) SetData(v []*Data) {
	x.xxx_hidden_Data = &v
}

func (x *PollResponse) HasServerVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PollResponse) ClearServerVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ServerVersion = 0
}

type PollResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ServerVersion *int32
	Data          []*Data
}

func (b0 PollResponse_builder) Build() *PollResponse {
	m0 := &PollResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ServerVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_ServerVersion = *b.ServerVersion
	}
	x.xxx_hidden_Data = &b.Data
	return m0
}

type Poll struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ServerVersion int32                  `protobuf:"varint,1,opt,name=server_version,json=serverVersion"`
	xxx_hidden_Type          RequestType            `protobuf:"varint,2,opt,name=type,enum=go.RequestType"`
	xxx_hidden_Data          *Data                  `protobuf:"bytes,3,opt,name=data"`
	xxx_hidden_Chunk         []byte                 `protobuf:"bytes,4,opt,name=chunk"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Poll) Reset() {
	*x = Poll{}
	mi := &file_app_api_proto_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Poll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poll) ProtoMessage() {}

func (x *Poll) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Poll) GetServerVersion() int32 {
	if x != nil {
		return x.xxx_hidden_ServerVersion
	}
	return 0
}

func (x *Poll) GetType() RequestType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Type
		}
	}
	return RequestType_Default
}

func (x *Poll) GetData() *Data {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Poll) GetChunk() []byte {
	if x != nil {
		return x.xxx_hidden_Chunk
	}
	return nil
}

func (x *Poll) SetServerVersion(v int32) {
	x.xxx_hidden_ServerVersion = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Poll) SetType(v RequestType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Poll) SetData(v *Data) {
	x.xxx_hidden_Data = v
}

func (x *Poll) SetChunk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Chunk = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *Poll) HasServerVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Poll) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Poll) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *Poll) HasChunk() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Poll) ClearServerVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ServerVersion = 0
}

func (x *Poll) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = RequestType_Default
}

func (x *Poll) ClearData() {
	x.xxx_hidden_Data = nil
}

func (x *Poll) ClearChunk() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Chunk = nil
}

type Poll_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ServerVersion *int32
	Type          *RequestType
	Data          *Data
	Chunk         []byte
}

func (b0 Poll_builder) Build() *Poll {
	m0 := &Poll{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ServerVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_ServerVersion = *b.ServerVersion
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Type = *b.Type
	}
	x.xxx_hidden_Data = b.Data
	if b.Chunk != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Chunk = b.Chunk
	}
	return m0
}

var File_app_api_proto_data_proto protoreflect.FileDescriptor

const file_app_api_proto_data_proto_rawDesc = "" +
	"\n" +
	"\x18app/api/proto/data.proto\x12\x02go\x1a!google/protobuf/go_features.proto\"\xe3\x02\n" +
	"\x04Data\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.go.Data.DataTypeR\x04type\x12\x14\n" +
	"\x05large\x18\x04 \x01(\bR\x05large\x12\x1b\n" +
	"\tdek_nonce\x18\x05 \x01(\fR\bdekNonce\x12\x10\n" +
	"\x03dek\x18\x06 \x01(\fR\x03dek\x12\x1d\n" +
	"\n" +
	"data_nonce\x18\a \x01(\fR\tdataNonce\x12\x12\n" +
	"\x04data\x18\b \x01(\fR\x04data\x12&\n" +
	"\x0ffile_data_nonce\x18\t \x01(\fR\rfileDataNonce\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x05R\aversion\x12\x18\n" +
	"\adeleted\x18\v \x01(\bR\adeleted\"<\n" +
	"\bDataType\x12\r\n" +
	"\tLoginPass\x10\x00\x12\b\n" +
	"\x04Text\x10\x01\x12\f\n" +
	"\bBankCard\x10\x02\x12\t\n" +
	"\x05Other\x10\x03\"+\n" +
	"\vPushRequest\x12\x1c\n" +
	"\x04data\x18\x01 \x03(\v2\b.go.DataR\x04data\"_\n" +
	"\x04Push\x12\x1c\n" +
	"\x04data\x18\x01 \x01(\v2\b.go.DataR\x04data\x12#\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0f.go.RequestTypeR\x04type\x12\x14\n" +
	"\x05chunk\x18\x03 \x01(\fR\x05chunk\"(\n" +
	"\fPushResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\vPollRequest\x12\x14\n" +
	"\x05since\x18\x01 \x01(\x05R\x05since\"S\n" +
	"\fPollResponse\x12%\n" +
	"\x0eserver_version\x18\x01 \x01(\x05R\rserverVersion\x12\x1c\n" +
	"\x04data\x18\x02 \x03(\v2\b.go.DataR\x04data\"\x86\x01\n" +
	"\x04Poll\x12%\n" +
	"\x0eserver_version\x18\x01 \x01(\x05R\rserverVersion\x12#\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0f.go.RequestTypeR\x04type\x12\x1c\n" +
	"\x04data\x18\x03 \x01(\v2\b.go.DataR\x04data\x12\x14\n" +
	"\x05chunk\x18\x04 \x01(\fR\x05chunk*Q\n" +
	"\vRequestType\x12\v\n" +
	"\aDefault\x10\x00\x12\r\n" +
	"\tStartData\x10\x01\x12\f\n" +
	"\bFilePart\x10\x02\x12\v\n" +
	"\aEndData\x10\x03\x12\v\n" +
	"\aErrData\x10\x042\xc1\x01\n" +
	"\bSyncData\x12.\n" +
	"\tPushUnary\x12\x0f.go.PushRequest\x1a\x10.go.PushResponse\x12*\n" +
	"\n" +
	"PushStream\x12\b.go.Push\x1a\x10.go.PushResponse(\x01\x12.\n" +
	"\tPollUnary\x12\x0f.go.PollRequest\x1a\x10.go.PollResponse\x12)\n" +
	"\n" +
	"PollStream\x12\x0f.go.PollRequest\x1a\b.go.Poll0\x01B\rZ\x03/pb\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_app_api_proto_data_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_app_api_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_app_api_proto_data_proto_goTypes = []any{
	(RequestType)(0),     // 0: go.RequestType
	(Data_DataType)(0),   // 1: go.Data.DataType
	(*Data)(nil),         // 2: go.Data
	(*PushRequest)(nil),  // 3: go.PushRequest
	(*Push)(nil),         // 4: go.Push
	(*PushResponse)(nil), // 5: go.PushResponse
	(*PollRequest)(nil),  // 6: go.PollRequest
	(*PollResponse)(nil), // 7: go.PollResponse
	(*Poll)(nil),         // 8: go.Poll
}
var file_app_api_proto_data_proto_depIdxs = []int32{
	1,  // 0: go.Data.type:type_name -> go.Data.DataType
	2,  // 1: go.PushRequest.data:type_name -> go.Data
	2,  // 2: go.Push.data:type_name -> go.Data
	0,  // 3: go.Push.type:type_name -> go.RequestType
	2,  // 4: go.PollResponse.data:type_name -> go.Data
	0,  // 5: go.Poll.type:type_name -> go.RequestType
	2,  // 6: go.Poll.data:type_name -> go.Data
	3,  // 7: go.SyncData.PushUnary:input_type -> go.PushRequest
	4,  // 8: go.SyncData.PushStream:input_type -> go.Push
	6,  // 9: go.SyncData.PollUnary:input_type -> go.PollRequest
	6,  // 10: go.SyncData.PollStream:input_type -> go.PollRequest
	5,  // 11: go.SyncData.PushUnary:output_type -> go.PushResponse
	5,  // 12: go.SyncData.PushStream:output_type -> go.PushResponse
	7,  // 13: go.SyncData.PollUnary:output_type -> go.PollResponse
	8,  // 14: go.SyncData.PollStream:output_type -> go.Poll
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_app_api_proto_data_proto_init() }
func file_app_api_proto_data_proto_init() {
	if File_app_api_proto_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_api_proto_data_proto_rawDesc), len(file_app_api_proto_data_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_api_proto_data_proto_goTypes,
		DependencyIndexes: file_app_api_proto_data_proto_depIdxs,
		EnumInfos:         file_app_api_proto_data_proto_enumTypes,
		MessageInfos:      file_app_api_proto_data_proto_msgTypes,
	}.Build()
	File_app_api_proto_data_proto = out.File
	file_app_api_proto_data_proto_goTypes = nil
	file_app_api_proto_data_proto_depIdxs = nil
}
