// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: app/api/proto/data.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncData_Push_FullMethodName       = "/go.SyncData/push"
	SyncData_Pull_FullMethodName       = "/go.SyncData/pull"
	SyncData_PushStream_FullMethodName = "/go.SyncData/PushStream"
	SyncData_PullStream_FullMethodName = "/go.SyncData/PullStream"
)

// SyncDataClient is the client API for SyncData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncDataClient interface {
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error)
	Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*PullResponse, error)
	PushStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Chunk, PushResponse], error)
	PullStream(ctx context.Context, in *PullStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error)
}

type syncDataClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncDataClient(cc grpc.ClientConnInterface) SyncDataClient {
	return &syncDataClient{cc}
}

func (c *syncDataClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, SyncData_Push_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncDataClient) Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*PullResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullResponse)
	err := c.cc.Invoke(ctx, SyncData_Pull_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncDataClient) PushStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Chunk, PushResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncData_ServiceDesc.Streams[0], SyncData_PushStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Chunk, PushResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncData_PushStreamClient = grpc.ClientStreamingClient[Chunk, PushResponse]

func (c *syncDataClient) PullStream(ctx context.Context, in *PullStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncData_ServiceDesc.Streams[1], SyncData_PullStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullStreamRequest, Chunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncData_PullStreamClient = grpc.ServerStreamingClient[Chunk]

// SyncDataServer is the server API for SyncData service.
// All implementations must embed UnimplementedSyncDataServer
// for forward compatibility.
type SyncDataServer interface {
	Push(context.Context, *PushRequest) (*PushResponse, error)
	Pull(context.Context, *PullRequest) (*PullResponse, error)
	PushStream(grpc.ClientStreamingServer[Chunk, PushResponse]) error
	PullStream(*PullStreamRequest, grpc.ServerStreamingServer[Chunk]) error
	mustEmbedUnimplementedSyncDataServer()
}

// UnimplementedSyncDataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncDataServer struct{}

func (UnimplementedSyncDataServer) Push(context.Context, *PushRequest) (*PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method push not implemented")
}
func (UnimplementedSyncDataServer) Pull(context.Context, *PullRequest) (*PullResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method pull not implemented")
}
func (UnimplementedSyncDataServer) PushStream(grpc.ClientStreamingServer[Chunk, PushResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PushStream not implemented")
}
func (UnimplementedSyncDataServer) PullStream(*PullStreamRequest, grpc.ServerStreamingServer[Chunk]) error {
	return status.Errorf(codes.Unimplemented, "method PullStream not implemented")
}
func (UnimplementedSyncDataServer) mustEmbedUnimplementedSyncDataServer() {}
func (UnimplementedSyncDataServer) testEmbeddedByValue()                  {}

// UnsafeSyncDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncDataServer will
// result in compilation errors.
type UnsafeSyncDataServer interface {
	mustEmbedUnimplementedSyncDataServer()
}

func RegisterSyncDataServer(s grpc.ServiceRegistrar, srv SyncDataServer) {
	// If the following call pancis, it indicates UnimplementedSyncDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncData_ServiceDesc, srv)
}

func _SyncData_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncDataServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncData_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncDataServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncData_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncDataServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncData_Pull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncDataServer).Pull(ctx, req.(*PullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncData_PushStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SyncDataServer).PushStream(&grpc.GenericServerStream[Chunk, PushResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncData_PushStreamServer = grpc.ClientStreamingServer[Chunk, PushResponse]

func _SyncData_PullStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SyncDataServer).PullStream(m, &grpc.GenericServerStream[PullStreamRequest, Chunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncData_PullStreamServer = grpc.ServerStreamingServer[Chunk]

// SyncData_ServiceDesc is the grpc.ServiceDesc for SyncData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go.SyncData",
	HandlerType: (*SyncDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "push",
			Handler:    _SyncData_Push_Handler,
		},
		{
			MethodName: "pull",
			Handler:    _SyncData_Pull_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushStream",
			Handler:       _SyncData_PushStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "PullStream",
			Handler:       _SyncData_PullStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "app/api/proto/data.proto",
}
