// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: app/api/proto/data.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkType int32

const (
	ChunkType_FilePart ChunkType = 0
	ChunkType_EndData  ChunkType = 1
	ChunkType_ErrData  ChunkType = 2
)

// Enum value maps for ChunkType.
var (
	ChunkType_name = map[int32]string{
		0: "FilePart",
		1: "EndData",
		2: "ErrData",
	}
	ChunkType_value = map[string]int32{
		"FilePart": 0,
		"EndData":  1,
		"ErrData":  2,
	}
)

func (x ChunkType) Enum() *ChunkType {
	p := new(ChunkType)
	*p = x
	return p
}

func (x ChunkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChunkType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_api_proto_data_proto_enumTypes[0].Descriptor()
}

func (ChunkType) Type() protoreflect.EnumType {
	return &file_app_api_proto_data_proto_enumTypes[0]
}

func (x ChunkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Secret_DataType int32

const (
	Secret_LoginPass Secret_DataType = 0
	Secret_Text      Secret_DataType = 1
	Secret_BankCard  Secret_DataType = 2
	Secret_Other     Secret_DataType = 3
)

// Enum value maps for Secret_DataType.
var (
	Secret_DataType_name = map[int32]string{
		0: "LoginPass",
		1: "Text",
		2: "BankCard",
		3: "Other",
	}
	Secret_DataType_value = map[string]int32{
		"LoginPass": 0,
		"Text":      1,
		"BankCard":  2,
		"Other":     3,
	}
)

func (x Secret_DataType) Enum() *Secret_DataType {
	p := new(Secret_DataType)
	*p = x
	return p
}

func (x Secret_DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Secret_DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_api_proto_data_proto_enumTypes[1].Descriptor()
}

func (Secret_DataType) Type() protoreflect.EnumType {
	return &file_app_api_proto_data_proto_enumTypes[1]
}

func (x Secret_DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Secret struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_ModifiedAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=modified_at,json=modifiedAt"`
	xxx_hidden_Type        Secret_DataType        `protobuf:"varint,3,opt,name=type,enum=go.Secret_DataType"`
	xxx_hidden_IsBig       bool                   `protobuf:"varint,4,opt,name=is_big,json=isBig"`
	xxx_hidden_Version     int32                  `protobuf:"varint,5,opt,name=version"`
	xxx_hidden_Deleted     bool                   `protobuf:"varint,6,opt,name=deleted"`
	xxx_hidden_Dek         []byte                 `protobuf:"bytes,7,opt,name=dek"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,8,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_app_api_proto_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Secret) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Secret) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ModifiedAt
	}
	return nil
}

func (x *Secret) GetType() Secret_DataType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Type
		}
	}
	return Secret_LoginPass
}

func (x *Secret) GetIsBig() bool {
	if x != nil {
		return x.xxx_hidden_IsBig
	}
	return false
}

func (x *Secret) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *Secret) GetDeleted() bool {
	if x != nil {
		return x.xxx_hidden_Deleted
	}
	return false
}

func (x *Secret) GetDek() []byte {
	if x != nil {
		return x.xxx_hidden_Dek
	}
	return nil
}

func (x *Secret) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Secret) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *Secret) SetModifiedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ModifiedAt = v
}

func (x *Secret) SetType(v Secret_DataType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *Secret) SetIsBig(v bool) {
	x.xxx_hidden_IsBig = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *Secret) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *Secret) SetDeleted(v bool) {
	x.xxx_hidden_Deleted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *Secret) SetDek(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Dek = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *Secret) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *Secret) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Secret) HasModifiedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ModifiedAt != nil
}

func (x *Secret) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Secret) HasIsBig() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Secret) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Secret) HasDeleted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Secret) HasDek() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Secret) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *Secret) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Secret) ClearModifiedAt() {
	x.xxx_hidden_ModifiedAt = nil
}

func (x *Secret) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Type = Secret_LoginPass
}

func (x *Secret) ClearIsBig() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_IsBig = false
}

func (x *Secret) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Version = 0
}

func (x *Secret) ClearDeleted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Deleted = false
}

func (x *Secret) ClearDek() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Dek = nil
}

func (x *Secret) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Data = nil
}

type Secret_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id         *string
	ModifiedAt *timestamppb.Timestamp
	Type       *Secret_DataType
	IsBig      *bool
	Version    *int32
	Deleted    *bool
	Dek        []byte
	Data       []byte
}

func (b0 Secret_builder) Build() *Secret {
	m0 := &Secret{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_ModifiedAt = b.ModifiedAt
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Type = *b.Type
	}
	if b.IsBig != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_IsBig = *b.IsBig
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Version = *b.Version
	}
	if b.Deleted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_Deleted = *b.Deleted
	}
	if b.Dek != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_Dek = b.Dek
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_Data = b.Data
	}
	return m0
}

type PushRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secrets     *[]*Secret             `protobuf:"bytes,1,rep,name=secrets"`
	xxx_hidden_Force       bool                   `protobuf:"varint,2,opt,name=force"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_app_api_proto_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PushRequest) GetSecrets() []*Secret {
	if x != nil {
		if x.xxx_hidden_Secrets != nil {
			return *x.xxx_hidden_Secrets
		}
	}
	return nil
}

func (x *PushRequest) GetForce() bool {
	if x != nil {
		return x.xxx_hidden_Force
	}
	return false
}

func (x *PushRequest) SetSecrets(v []*Secret) {
	x.xxx_hidden_Secrets = &v
}

func (x *PushRequest) SetForce(v bool) {
	x.xxx_hidden_Force = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *PushRequest) HasForce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PushRequest) ClearForce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Force = false
}

type PushRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secrets []*Secret
	Force   *bool
}

func (b0 PushRequest_builder) Build() *PushRequest {
	m0 := &PushRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secrets = &b.Secrets
	if b.Force != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Force = *b.Force
	}
	return m0
}

type Chunk struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Type        ChunkType              `protobuf:"varint,2,opt,name=type,enum=go.ChunkType"`
	xxx_hidden_Buffer      []byte                 `protobuf:"bytes,3,opt,name=buffer"`
	xxx_hidden_Version     int32                  `protobuf:"varint,4,opt,name=version"`
	xxx_hidden_Secret      *Secret                `protobuf:"bytes,5,opt,name=secret"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_app_api_proto_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Chunk) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Chunk) GetType() ChunkType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Type
		}
	}
	return ChunkType_FilePart
}

func (x *Chunk) GetBuffer() []byte {
	if x != nil {
		return x.xxx_hidden_Buffer
	}
	return nil
}

func (x *Chunk) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *Chunk) GetSecret() *Secret {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return nil
}

func (x *Chunk) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Chunk) SetType(v ChunkType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *Chunk) SetBuffer(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Buffer = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *Chunk) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *Chunk) SetSecret(v *Secret) {
	x.xxx_hidden_Secret = v
}

func (x *Chunk) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Chunk) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Chunk) HasBuffer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Chunk) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Chunk) HasSecret() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Secret != nil
}

func (x *Chunk) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Chunk) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = ChunkType_FilePart
}

func (x *Chunk) ClearBuffer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Buffer = nil
}

func (x *Chunk) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Version = 0
}

func (x *Chunk) ClearSecret() {
	x.xxx_hidden_Secret = nil
}

type Chunk_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      *string
	Type    *ChunkType
	Buffer  []byte
	Version *int32
	Secret  *Secret
}

func (b0 Chunk_builder) Build() *Chunk {
	m0 := &Chunk{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Id = b.Id
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Buffer != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Buffer = b.Buffer
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Version = *b.Version
	}
	x.xxx_hidden_Secret = b.Secret
	return m0
}

type PushResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success     bool                   `protobuf:"varint,1,opt,name=success"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_app_api_proto_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PushResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *PushResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *PushResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PushResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Success = false
}

type PushResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success *bool
}

func (b0 PushResponse_builder) Build() *PushResponse {
	m0 := &PushResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Success = *b.Success
	}
	return m0
}

type PullRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Since       int32                  `protobuf:"varint,2,opt,name=since"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_app_api_proto_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PullRequest) GetSince() int32 {
	if x != nil {
		return x.xxx_hidden_Since
	}
	return 0
}

func (x *PullRequest) SetSince(v int32) {
	x.xxx_hidden_Since = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *PullRequest) HasSince() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PullRequest) ClearSince() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Since = 0
}

type PullRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Since *int32
}

func (b0 PullRequest_builder) Build() *PullRequest {
	m0 := &PullRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Since != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Since = *b.Since
	}
	return m0
}

type PullResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secrets     *[]*Secret             `protobuf:"bytes,1,rep,name=secrets"`
	xxx_hidden_Version     int32                  `protobuf:"varint,2,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PullResponse) Reset() {
	*x = PullResponse{}
	mi := &file_app_api_proto_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullResponse) ProtoMessage() {}

func (x *PullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PullResponse) GetSecrets() []*Secret {
	if x != nil {
		if x.xxx_hidden_Secrets != nil {
			return *x.xxx_hidden_Secrets
		}
	}
	return nil
}

func (x *PullResponse) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *PullResponse) SetSecrets(v []*Secret) {
	x.xxx_hidden_Secrets = &v
}

func (x *PullResponse) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *PullResponse) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PullResponse) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Version = 0
}

type PullResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secrets []*Secret
	Version *int32
}

func (b0 PullResponse_builder) Build() *PullResponse {
	m0 := &PullResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secrets = &b.Secrets
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

type PullStreamRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Version     int32                  `protobuf:"varint,2,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PullStreamRequest) Reset() {
	*x = PullStreamRequest{}
	mi := &file_app_api_proto_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullStreamRequest) ProtoMessage() {}

func (x *PullStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PullStreamRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *PullStreamRequest) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *PullStreamRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *PullStreamRequest) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *PullStreamRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PullStreamRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PullStreamRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *PullStreamRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Version = 0
}

type PullStreamRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      *string
	Version *int32
}

func (b0 PullStreamRequest_builder) Build() *PullStreamRequest {
	m0 := &PullStreamRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

var File_app_api_proto_data_proto protoreflect.FileDescriptor

const file_app_api_proto_data_proto_rawDesc = "" +
	"\n" +
	"\x18app/api/proto/data.proto\x12\x02go\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!google/protobuf/go_features.proto\"\xad\x02\n" +
	"\x06Secret\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\vmodified_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.go.Secret.DataTypeR\x04type\x12\x15\n" +
	"\x06is_big\x18\x04 \x01(\bR\x05isBig\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x12\x18\n" +
	"\adeleted\x18\x06 \x01(\bR\adeleted\x12\x10\n" +
	"\x03dek\x18\a \x01(\fR\x03dek\x12\x12\n" +
	"\x04data\x18\b \x01(\fR\x04data\"<\n" +
	"\bDataType\x12\r\n" +
	"\tLoginPass\x10\x00\x12\b\n" +
	"\x04Text\x10\x01\x12\f\n" +
	"\bBankCard\x10\x02\x12\t\n" +
	"\x05Other\x10\x03\"I\n" +
	"\vPushRequest\x12$\n" +
	"\asecrets\x18\x01 \x03(\v2\n" +
	".go.SecretR\asecrets\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\x90\x01\n" +
	"\x05Chunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\x04type\x18\x02 \x01(\x0e2\r.go.ChunkTypeR\x04type\x12\x16\n" +
	"\x06buffer\x18\x03 \x01(\fR\x06buffer\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12\"\n" +
	"\x06secret\x18\x05 \x01(\v2\n" +
	".go.SecretR\x06secret\"(\n" +
	"\fPushResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\vPullRequest\x12\x14\n" +
	"\x05since\x18\x02 \x01(\x05R\x05since\"N\n" +
	"\fPullResponse\x12$\n" +
	"\asecrets\x18\x01 \x03(\v2\n" +
	".go.SecretR\asecrets\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"=\n" +
	"\x11PullStreamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion*3\n" +
	"\tChunkType\x12\f\n" +
	"\bFilePart\x10\x00\x12\v\n" +
	"\aEndData\x10\x01\x12\v\n" +
	"\aErrData\x10\x022\xbf\x01\n" +
	"\bSyncData\x12)\n" +
	"\x04Push\x12\x0f.go.PushRequest\x1a\x10.go.PushResponse\x12)\n" +
	"\x04Pull\x12\x0f.go.PullRequest\x1a\x10.go.PullResponse\x12+\n" +
	"\n" +
	"PushStream\x12\t.go.Chunk\x1a\x10.go.PushResponse(\x01\x120\n" +
	"\n" +
	"PullStream\x12\x15.go.PullStreamRequest\x1a\t.go.Chunk0\x01B\rZ\x03/pb\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_app_api_proto_data_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_app_api_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_app_api_proto_data_proto_goTypes = []any{
	(ChunkType)(0),                // 0: go.ChunkType
	(Secret_DataType)(0),          // 1: go.Secret.DataType
	(*Secret)(nil),                // 2: go.Secret
	(*PushRequest)(nil),           // 3: go.PushRequest
	(*Chunk)(nil),                 // 4: go.Chunk
	(*PushResponse)(nil),          // 5: go.PushResponse
	(*PullRequest)(nil),           // 6: go.PullRequest
	(*PullResponse)(nil),          // 7: go.PullResponse
	(*PullStreamRequest)(nil),     // 8: go.PullStreamRequest
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_app_api_proto_data_proto_depIdxs = []int32{
	9,  // 0: go.Secret.modified_at:type_name -> google.protobuf.Timestamp
	1,  // 1: go.Secret.type:type_name -> go.Secret.DataType
	2,  // 2: go.PushRequest.secrets:type_name -> go.Secret
	0,  // 3: go.Chunk.type:type_name -> go.ChunkType
	2,  // 4: go.Chunk.secret:type_name -> go.Secret
	2,  // 5: go.PullResponse.secrets:type_name -> go.Secret
	3,  // 6: go.SyncData.push:input_type -> go.PushRequest
	6,  // 7: go.SyncData.pull:input_type -> go.PullRequest
	4,  // 8: go.SyncData.PushStream:input_type -> go.Chunk
	8,  // 9: go.SyncData.PullStream:input_type -> go.PullStreamRequest
	5,  // 10: go.SyncData.push:output_type -> go.PushResponse
	7,  // 11: go.SyncData.pull:output_type -> go.PullResponse
	5,  // 12: go.SyncData.PushStream:output_type -> go.PushResponse
	4,  // 13: go.SyncData.PullStream:output_type -> go.Chunk
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_app_api_proto_data_proto_init() }
func file_app_api_proto_data_proto_init() {
	if File_app_api_proto_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_api_proto_data_proto_rawDesc), len(file_app_api_proto_data_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_api_proto_data_proto_goTypes,
		DependencyIndexes: file_app_api_proto_data_proto_depIdxs,
		EnumInfos:         file_app_api_proto_data_proto_enumTypes,
		MessageInfos:      file_app_api_proto_data_proto_msgTypes,
	}.Build()
	File_app_api_proto_data_proto = out.File
	file_app_api_proto_data_proto_goTypes = nil
	file_app_api_proto_data_proto_depIdxs = nil
}
