// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: app/api/proto/data.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncData_Push_FullMethodName = "/go.SyncData/Push"
	SyncData_Poll_FullMethodName = "/go.SyncData/Poll"
)

// SyncDataClient is the client API for SyncData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncDataClient interface {
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error)
	Poll(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*PollResponse, error)
}

type syncDataClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncDataClient(cc grpc.ClientConnInterface) SyncDataClient {
	return &syncDataClient{cc}
}

func (c *syncDataClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, SyncData_Push_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncDataClient) Poll(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*PollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollResponse)
	err := c.cc.Invoke(ctx, SyncData_Poll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncDataServer is the server API for SyncData service.
// All implementations must embed UnimplementedSyncDataServer
// for forward compatibility.
type SyncDataServer interface {
	Push(context.Context, *PushRequest) (*PushResponse, error)
	Poll(context.Context, *PollRequest) (*PollResponse, error)
	mustEmbedUnimplementedSyncDataServer()
}

// UnimplementedSyncDataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncDataServer struct{}

func (UnimplementedSyncDataServer) Push(context.Context, *PushRequest) (*PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedSyncDataServer) Poll(context.Context, *PollRequest) (*PollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Poll not implemented")
}
func (UnimplementedSyncDataServer) mustEmbedUnimplementedSyncDataServer() {}
func (UnimplementedSyncDataServer) testEmbeddedByValue()                  {}

// UnsafeSyncDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncDataServer will
// result in compilation errors.
type UnsafeSyncDataServer interface {
	mustEmbedUnimplementedSyncDataServer()
}

func RegisterSyncDataServer(s grpc.ServiceRegistrar, srv SyncDataServer) {
	// If the following call pancis, it indicates UnimplementedSyncDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncData_ServiceDesc, srv)
}

func _SyncData_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncDataServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncData_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncDataServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncData_Poll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncDataServer).Poll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncData_Poll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncDataServer).Poll(ctx, req.(*PollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncData_ServiceDesc is the grpc.ServiceDesc for SyncData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go.SyncData",
	HandlerType: (*SyncDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _SyncData_Push_Handler,
		},
		{
			MethodName: "Poll",
			Handler:    _SyncData_Poll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/api/proto/data.proto",
}
