// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: app/api/proto/sync.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretType int32

const (
	SecretType_LoginPass SecretType = 0
	SecretType_Text      SecretType = 1
	SecretType_BankCard  SecretType = 2
	SecretType_Binary    SecretType = 3
)

// Enum value maps for SecretType.
var (
	SecretType_name = map[int32]string{
		0: "LoginPass",
		1: "Text",
		2: "BankCard",
		3: "Binary",
	}
	SecretType_value = map[string]int32{
		"LoginPass": 0,
		"Text":      1,
		"BankCard":  2,
		"Binary":    3,
	}
)

func (x SecretType) Enum() *SecretType {
	p := new(SecretType)
	*p = x
	return p
}

func (x SecretType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_api_proto_sync_proto_enumTypes[0].Descriptor()
}

func (SecretType) Type() protoreflect.EnumType {
	return &file_app_api_proto_sync_proto_enumTypes[0]
}

func (x SecretType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type OperationType int32

const (
	OperationType_Default    OperationType = 0
	OperationType_Begin      OperationType = 1
	OperationType_BinaryPart OperationType = 2
	OperationType_End        OperationType = 3
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "Default",
		1: "Begin",
		2: "BinaryPart",
		3: "End",
	}
	OperationType_value = map[string]int32{
		"Default":    0,
		"Begin":      1,
		"BinaryPart": 2,
		"End":        3,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_api_proto_sync_proto_enumTypes[1].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_app_api_proto_sync_proto_enumTypes[1]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ChunkType int32

const (
	ChunkType_FilePart ChunkType = 0
	ChunkType_EndData  ChunkType = 1
	ChunkType_ErrData  ChunkType = 2
)

// Enum value maps for ChunkType.
var (
	ChunkType_name = map[int32]string{
		0: "FilePart",
		1: "EndData",
		2: "ErrData",
	}
	ChunkType_value = map[string]int32{
		"FilePart": 0,
		"EndData":  1,
		"ErrData":  2,
	}
)

func (x ChunkType) Enum() *ChunkType {
	p := new(ChunkType)
	*p = x
	return p
}

func (x ChunkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChunkType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_api_proto_sync_proto_enumTypes[2].Descriptor()
}

func (ChunkType) Type() protoreflect.EnumType {
	return &file_app_api_proto_sync_proto_enumTypes[2]
}

func (x ChunkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Secret struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_ModifiedAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=modified_at,json=modifiedAt"`
	xxx_hidden_Type        SecretType             `protobuf:"varint,3,opt,name=type,enum=go.SecretType"`
	xxx_hidden_IsBig       bool                   `protobuf:"varint,4,opt,name=is_big,json=isBig"`
	xxx_hidden_Version     int32                  `protobuf:"varint,5,opt,name=version"`
	xxx_hidden_Deleted     bool                   `protobuf:"varint,6,opt,name=deleted"`
	xxx_hidden_Dek         []byte                 `protobuf:"bytes,7,opt,name=dek"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,8,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_app_api_proto_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Secret) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Secret) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ModifiedAt
	}
	return nil
}

func (x *Secret) GetType() SecretType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Type
		}
	}
	return SecretType_LoginPass
}

func (x *Secret) GetIsBig() bool {
	if x != nil {
		return x.xxx_hidden_IsBig
	}
	return false
}

func (x *Secret) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *Secret) GetDeleted() bool {
	if x != nil {
		return x.xxx_hidden_Deleted
	}
	return false
}

func (x *Secret) GetDek() []byte {
	if x != nil {
		return x.xxx_hidden_Dek
	}
	return nil
}

func (x *Secret) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Secret) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *Secret) SetModifiedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ModifiedAt = v
}

func (x *Secret) SetType(v SecretType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *Secret) SetIsBig(v bool) {
	x.xxx_hidden_IsBig = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *Secret) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *Secret) SetDeleted(v bool) {
	x.xxx_hidden_Deleted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *Secret) SetDek(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Dek = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *Secret) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *Secret) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Secret) HasModifiedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ModifiedAt != nil
}

func (x *Secret) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Secret) HasIsBig() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Secret) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Secret) HasDeleted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Secret) HasDek() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Secret) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *Secret) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Secret) ClearModifiedAt() {
	x.xxx_hidden_ModifiedAt = nil
}

func (x *Secret) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Type = SecretType_LoginPass
}

func (x *Secret) ClearIsBig() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_IsBig = false
}

func (x *Secret) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Version = 0
}

func (x *Secret) ClearDeleted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Deleted = false
}

func (x *Secret) ClearDek() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Dek = nil
}

func (x *Secret) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Data = nil
}

type Secret_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id         *string
	ModifiedAt *timestamppb.Timestamp
	Type       *SecretType
	IsBig      *bool
	Version    *int32
	Deleted    *bool
	Dek        []byte
	Data       []byte
}

func (b0 Secret_builder) Build() *Secret {
	m0 := &Secret{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_ModifiedAt = b.ModifiedAt
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Type = *b.Type
	}
	if b.IsBig != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_IsBig = *b.IsBig
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Version = *b.Version
	}
	if b.Deleted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_Deleted = *b.Deleted
	}
	if b.Dek != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_Dek = b.Dek
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_Data = b.Data
	}
	return m0
}

type PushOperation struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secret      *Secret                `protobuf:"bytes,1,opt,name=secret"`
	xxx_hidden_Type        OperationType          `protobuf:"varint,2,opt,name=type,enum=go.OperationType"`
	xxx_hidden_Buffer      []byte                 `protobuf:"bytes,3,opt,name=buffer"`
	xxx_hidden_ChunkNumber []byte                 `protobuf:"bytes,4,opt,name=chunk_number,json=chunkNumber"`
	xxx_hidden_ChunkCount  []byte                 `protobuf:"bytes,5,opt,name=chunk_count,json=chunkCount"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PushOperation) Reset() {
	*x = PushOperation{}
	mi := &file_app_api_proto_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushOperation) ProtoMessage() {}

func (x *PushOperation) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PushOperation) GetSecret() *Secret {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return nil
}

func (x *PushOperation) GetType() OperationType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Type
		}
	}
	return OperationType_Default
}

func (x *PushOperation) GetBuffer() []byte {
	if x != nil {
		return x.xxx_hidden_Buffer
	}
	return nil
}

func (x *PushOperation) GetChunkNumber() []byte {
	if x != nil {
		return x.xxx_hidden_ChunkNumber
	}
	return nil
}

func (x *PushOperation) GetChunkCount() []byte {
	if x != nil {
		return x.xxx_hidden_ChunkCount
	}
	return nil
}

func (x *PushOperation) SetSecret(v *Secret) {
	x.xxx_hidden_Secret = v
}

func (x *PushOperation) SetType(v OperationType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *PushOperation) SetBuffer(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Buffer = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *PushOperation) SetChunkNumber(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ChunkNumber = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *PushOperation) SetChunkCount(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ChunkCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *PushOperation) HasSecret() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Secret != nil
}

func (x *PushOperation) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PushOperation) HasBuffer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PushOperation) HasChunkNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *PushOperation) HasChunkCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *PushOperation) ClearSecret() {
	x.xxx_hidden_Secret = nil
}

func (x *PushOperation) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = OperationType_Default
}

func (x *PushOperation) ClearBuffer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Buffer = nil
}

func (x *PushOperation) ClearChunkNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ChunkNumber = nil
}

func (x *PushOperation) ClearChunkCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_ChunkCount = nil
}

type PushOperation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secret      *Secret
	Type        *OperationType
	Buffer      []byte
	ChunkNumber []byte
	ChunkCount  []byte
}

func (b0 PushOperation_builder) Build() *PushOperation {
	m0 := &PushOperation{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secret = b.Secret
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Buffer != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Buffer = b.Buffer
	}
	if b.ChunkNumber != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_ChunkNumber = b.ChunkNumber
	}
	if b.ChunkCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_ChunkCount = b.ChunkCount
	}
	return m0
}

type Chunk struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Type        ChunkType              `protobuf:"varint,2,opt,name=type,enum=go.ChunkType"`
	xxx_hidden_Buffer      []byte                 `protobuf:"bytes,3,opt,name=buffer"`
	xxx_hidden_Version     int32                  `protobuf:"varint,4,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_app_api_proto_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Chunk) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Chunk) GetType() ChunkType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Type
		}
	}
	return ChunkType_FilePart
}

func (x *Chunk) GetBuffer() []byte {
	if x != nil {
		return x.xxx_hidden_Buffer
	}
	return nil
}

func (x *Chunk) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *Chunk) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Chunk) SetType(v ChunkType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Chunk) SetBuffer(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Buffer = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Chunk) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *Chunk) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Chunk) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Chunk) HasBuffer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Chunk) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Chunk) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Chunk) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = ChunkType_FilePart
}

func (x *Chunk) ClearBuffer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Buffer = nil
}

func (x *Chunk) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Version = 0
}

type Chunk_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      *string
	Type    *ChunkType
	Buffer  []byte
	Version *int32
}

func (b0 Chunk_builder) Build() *Chunk {
	m0 := &Chunk{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Id = b.Id
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Buffer != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Buffer = b.Buffer
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

type PushResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success     bool                   `protobuf:"varint,1,opt,name=success"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_app_api_proto_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PushResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *PushResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *PushResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PushResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Success = false
}

type PushResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success *bool
}

func (b0 PushResponse_builder) Build() *PushResponse {
	m0 := &PushResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Success = *b.Success
	}
	return m0
}

type PullRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Since       int32                  `protobuf:"varint,2,opt,name=since"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_app_api_proto_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PullRequest) GetSince() int32 {
	if x != nil {
		return x.xxx_hidden_Since
	}
	return 0
}

func (x *PullRequest) SetSince(v int32) {
	x.xxx_hidden_Since = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *PullRequest) HasSince() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PullRequest) ClearSince() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Since = 0
}

type PullRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Since *int32
}

func (b0 PullRequest_builder) Build() *PullRequest {
	m0 := &PullRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Since != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Since = *b.Since
	}
	return m0
}

type PullResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secrets     *[]*Secret             `protobuf:"bytes,1,rep,name=secrets"`
	xxx_hidden_Version     int32                  `protobuf:"varint,2,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PullResponse) Reset() {
	*x = PullResponse{}
	mi := &file_app_api_proto_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullResponse) ProtoMessage() {}

func (x *PullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PullResponse) GetSecrets() []*Secret {
	if x != nil {
		if x.xxx_hidden_Secrets != nil {
			return *x.xxx_hidden_Secrets
		}
	}
	return nil
}

func (x *PullResponse) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *PullResponse) SetSecrets(v []*Secret) {
	x.xxx_hidden_Secrets = &v
}

func (x *PullResponse) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *PullResponse) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PullResponse) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Version = 0
}

type PullResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secrets []*Secret
	Version *int32
}

func (b0 PullResponse_builder) Build() *PullResponse {
	m0 := &PullResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secrets = &b.Secrets
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

type PullStreamRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Version     int32                  `protobuf:"varint,2,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PullStreamRequest) Reset() {
	*x = PullStreamRequest{}
	mi := &file_app_api_proto_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullStreamRequest) ProtoMessage() {}

func (x *PullStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PullStreamRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *PullStreamRequest) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *PullStreamRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *PullStreamRequest) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *PullStreamRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PullStreamRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PullStreamRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *PullStreamRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Version = 0
}

type PullStreamRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      *string
	Version *int32
}

func (b0 PullStreamRequest_builder) Build() *PullStreamRequest {
	m0 := &PullStreamRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

var File_app_api_proto_sync_proto protoreflect.FileDescriptor

const file_app_api_proto_sync_proto_rawDesc = "" +
	"\n" +
	"\x18app/api/proto/sync.proto\x12\x02go\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!google/protobuf/go_features.proto\"\xea\x01\n" +
	"\x06Secret\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\vmodified_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12\"\n" +
	"\x04type\x18\x03 \x01(\x0e2\x0e.go.SecretTypeR\x04type\x12\x15\n" +
	"\x06is_big\x18\x04 \x01(\bR\x05isBig\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x12\x18\n" +
	"\adeleted\x18\x06 \x01(\bR\adeleted\x12\x10\n" +
	"\x03dek\x18\a \x01(\fR\x03dek\x12\x12\n" +
	"\x04data\x18\b \x01(\fR\x04data\"\xb6\x01\n" +
	"\rPushOperation\x12\"\n" +
	"\x06secret\x18\x01 \x01(\v2\n" +
	".go.SecretR\x06secret\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.go.OperationTypeR\x04type\x12\x16\n" +
	"\x06buffer\x18\x03 \x01(\fR\x06buffer\x12!\n" +
	"\fchunk_number\x18\x04 \x01(\fR\vchunkNumber\x12\x1f\n" +
	"\vchunk_count\x18\x05 \x01(\fR\n" +
	"chunkCount\"l\n" +
	"\x05Chunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\x04type\x18\x02 \x01(\x0e2\r.go.ChunkTypeR\x04type\x12\x16\n" +
	"\x06buffer\x18\x03 \x01(\fR\x06buffer\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\"(\n" +
	"\fPushResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\vPullRequest\x12\x14\n" +
	"\x05since\x18\x02 \x01(\x05R\x05since\"N\n" +
	"\fPullResponse\x12$\n" +
	"\asecrets\x18\x01 \x03(\v2\n" +
	".go.SecretR\asecrets\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"=\n" +
	"\x11PullStreamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion*?\n" +
	"\n" +
	"SecretType\x12\r\n" +
	"\tLoginPass\x10\x00\x12\b\n" +
	"\x04Text\x10\x01\x12\f\n" +
	"\bBankCard\x10\x02\x12\n" +
	"\n" +
	"\x06Binary\x10\x03*@\n" +
	"\rOperationType\x12\v\n" +
	"\aDefault\x10\x00\x12\t\n" +
	"\x05Begin\x10\x01\x12\x0e\n" +
	"\n" +
	"BinaryPart\x10\x02\x12\a\n" +
	"\x03End\x10\x03*3\n" +
	"\tChunkType\x12\f\n" +
	"\bFilePart\x10\x00\x12\v\n" +
	"\aEndData\x10\x01\x12\v\n" +
	"\aErrData\x10\x022\x98\x01\n" +
	"\x04Sync\x123\n" +
	"\n" +
	"PushStream\x12\x11.go.PushOperation\x1a\x10.go.PushResponse(\x01\x12)\n" +
	"\x04Pull\x12\x0f.go.PullRequest\x1a\x10.go.PullResponse\x120\n" +
	"\n" +
	"PullStream\x12\x15.go.PullStreamRequest\x1a\t.go.Chunk0\x01B\rZ\x03/pb\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_app_api_proto_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_app_api_proto_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_app_api_proto_sync_proto_goTypes = []any{
	(SecretType)(0),               // 0: go.SecretType
	(OperationType)(0),            // 1: go.OperationType
	(ChunkType)(0),                // 2: go.ChunkType
	(*Secret)(nil),                // 3: go.Secret
	(*PushOperation)(nil),         // 4: go.PushOperation
	(*Chunk)(nil),                 // 5: go.Chunk
	(*PushResponse)(nil),          // 6: go.PushResponse
	(*PullRequest)(nil),           // 7: go.PullRequest
	(*PullResponse)(nil),          // 8: go.PullResponse
	(*PullStreamRequest)(nil),     // 9: go.PullStreamRequest
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_app_api_proto_sync_proto_depIdxs = []int32{
	10, // 0: go.Secret.modified_at:type_name -> google.protobuf.Timestamp
	0,  // 1: go.Secret.type:type_name -> go.SecretType
	3,  // 2: go.PushOperation.secret:type_name -> go.Secret
	1,  // 3: go.PushOperation.type:type_name -> go.OperationType
	2,  // 4: go.Chunk.type:type_name -> go.ChunkType
	3,  // 5: go.PullResponse.secrets:type_name -> go.Secret
	4,  // 6: go.Sync.PushStream:input_type -> go.PushOperation
	7,  // 7: go.Sync.Pull:input_type -> go.PullRequest
	9,  // 8: go.Sync.PullStream:input_type -> go.PullStreamRequest
	6,  // 9: go.Sync.PushStream:output_type -> go.PushResponse
	8,  // 10: go.Sync.Pull:output_type -> go.PullResponse
	5,  // 11: go.Sync.PullStream:output_type -> go.Chunk
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_app_api_proto_sync_proto_init() }
func file_app_api_proto_sync_proto_init() {
	if File_app_api_proto_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_api_proto_sync_proto_rawDesc), len(file_app_api_proto_sync_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_api_proto_sync_proto_goTypes,
		DependencyIndexes: file_app_api_proto_sync_proto_depIdxs,
		EnumInfos:         file_app_api_proto_sync_proto_enumTypes,
		MessageInfos:      file_app_api_proto_sync_proto_msgTypes,
	}.Build()
	File_app_api_proto_sync_proto = out.File
	file_app_api_proto_sync_proto_goTypes = nil
	file_app_api_proto_sync_proto_depIdxs = nil
}
