// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: app/api/proto/data.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationType int32

const (
	OperationType_Insert OperationType = 0
	OperationType_Update OperationType = 1
	OperationType_Delete OperationType = 2
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "Insert",
		1: "Update",
		2: "Delete",
	}
	OperationType_value = map[string]int32{
		"Insert": 0,
		"Update": 1,
		"Delete": 2,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_api_proto_data_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_app_api_proto_data_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Data_DataType int32

const (
	Data_LoginPass Data_DataType = 0
	Data_Text      Data_DataType = 1
	Data_BankCard  Data_DataType = 2
	Data_Other     Data_DataType = 3
)

// Enum value maps for Data_DataType.
var (
	Data_DataType_name = map[int32]string{
		0: "LoginPass",
		1: "Text",
		2: "BankCard",
		3: "Other",
	}
	Data_DataType_value = map[string]int32{
		"LoginPass": 0,
		"Text":      1,
		"BankCard":  2,
		"Other":     3,
	}
)

func (x Data_DataType) Enum() *Data_DataType {
	p := new(Data_DataType)
	*p = x
	return p
}

func (x Data_DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Data_DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_api_proto_data_proto_enumTypes[1].Descriptor()
}

func (Data_DataType) Type() protoreflect.EnumType {
	return &file_app_api_proto_data_proto_enumTypes[1]
}

func (x Data_DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Data struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Type        Data_DataType          `protobuf:"varint,3,opt,name=type,enum=go.Data_DataType"`
	xxx_hidden_Large       bool                   `protobuf:"varint,4,opt,name=large"`
	xxx_hidden_DekNonce    []byte                 `protobuf:"bytes,5,opt,name=dek_nonce,json=dekNonce"`
	xxx_hidden_Dek         []byte                 `protobuf:"bytes,6,opt,name=dek"`
	xxx_hidden_DataNonce   []byte                 `protobuf:"bytes,7,opt,name=data_nonce,json=dataNonce"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,8,opt,name=data"`
	xxx_hidden_Version     int32                  `protobuf:"varint,9,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_app_api_proto_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Data) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Data) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Data) GetType() Data_DataType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Type
		}
	}
	return Data_LoginPass
}

func (x *Data) GetLarge() bool {
	if x != nil {
		return x.xxx_hidden_Large
	}
	return false
}

func (x *Data) GetDekNonce() []byte {
	if x != nil {
		return x.xxx_hidden_DekNonce
	}
	return nil
}

func (x *Data) GetDek() []byte {
	if x != nil {
		return x.xxx_hidden_Dek
	}
	return nil
}

func (x *Data) GetDataNonce() []byte {
	if x != nil {
		return x.xxx_hidden_DataNonce
	}
	return nil
}

func (x *Data) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Data) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *Data) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *Data) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *Data) SetType(v Data_DataType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *Data) SetLarge(v bool) {
	x.xxx_hidden_Large = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *Data) SetDekNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_DekNonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *Data) SetDek(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Dek = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *Data) SetDataNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_DataNonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *Data) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *Data) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *Data) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Data) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Data) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Data) HasLarge() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Data) HasDekNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Data) HasDek() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Data) HasDataNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Data) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *Data) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *Data) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Data) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *Data) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Type = Data_LoginPass
}

func (x *Data) ClearLarge() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Large = false
}

func (x *Data) ClearDekNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_DekNonce = nil
}

func (x *Data) ClearDek() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Dek = nil
}

func (x *Data) ClearDataNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_DataNonce = nil
}

func (x *Data) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Data = nil
}

func (x *Data) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Version = 0
}

type Data_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        *string
	Name      *string
	Type      *Data_DataType
	Large     *bool
	DekNonce  []byte
	Dek       []byte
	DataNonce []byte
	Data      []byte
	Version   *int32
}

func (b0 Data_builder) Build() *Data {
	m0 := &Data{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_Id = b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_Name = b.Name
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Large != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_Large = *b.Large
	}
	if b.DekNonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_DekNonce = b.DekNonce
	}
	if b.Dek != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_Dek = b.Dek
	}
	if b.DataNonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_DataNonce = b.DataNonce
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_Data = b.Data
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

type Operation struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data        *Data                  `protobuf:"bytes,1,opt,name=data"`
	xxx_hidden_Type        OperationType          `protobuf:"varint,2,opt,name=type,enum=go.OperationType"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_app_api_proto_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Operation) GetData() *Data {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Operation) GetType() OperationType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Type
		}
	}
	return OperationType_Insert
}

func (x *Operation) SetData(v *Data) {
	x.xxx_hidden_Data = v
}

func (x *Operation) SetType(v OperationType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Operation) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *Operation) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Operation) ClearData() {
	x.xxx_hidden_Data = nil
}

func (x *Operation) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = OperationType_Insert
}

type Operation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data *Data
	Type *OperationType
}

func (b0 Operation_builder) Build() *Operation {
	m0 := &Operation{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = b.Data
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Type = *b.Type
	}
	return m0
}

type PushRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Requests *[]*Operation          `protobuf:"bytes,1,rep,name=requests"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_app_api_proto_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PushRequest) GetRequests() []*Operation {
	if x != nil {
		if x.xxx_hidden_Requests != nil {
			return *x.xxx_hidden_Requests
		}
	}
	return nil
}

func (x *PushRequest) SetRequests(v []*Operation) {
	x.xxx_hidden_Requests = &v
}

type PushRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Requests []*Operation
}

func (b0 PushRequest_builder) Build() *PushRequest {
	m0 := &PushRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Requests = &b.Requests
	return m0
}

type OperationResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data *Data                  `protobuf:"bytes,1,opt,name=data"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_app_api_proto_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OperationResponse) GetData() *Data {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *OperationResponse) SetData(v *Data) {
	x.xxx_hidden_Data = v
}

func (x *OperationResponse) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *OperationResponse) ClearData() {
	x.xxx_hidden_Data = nil
}

type OperationResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data *Data
}

func (b0 OperationResponse_builder) Build() *OperationResponse {
	m0 := &OperationResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = b.Data
	return m0
}

type PushResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data *[]*OperationResponse  `protobuf:"bytes,1,rep,name=data"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_app_api_proto_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PushResponse) GetData() []*OperationResponse {
	if x != nil {
		if x.xxx_hidden_Data != nil {
			return *x.xxx_hidden_Data
		}
	}
	return nil
}

func (x *PushResponse) SetData(v []*OperationResponse) {
	x.xxx_hidden_Data = &v
}

type PushResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data []*OperationResponse
}

func (b0 PushResponse_builder) Build() *PushResponse {
	m0 := &PushResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = &b.Data
	return m0
}

type PollRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_app_api_proto_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PollRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PollRequest_builder) Build() *PollRequest {
	m0 := &PollRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_app_api_proto_data_proto protoreflect.FileDescriptor

const file_app_api_proto_data_proto_rawDesc = "" +
	"\n" +
	"\x18app/api/proto/data.proto\x12\x02go\x1a!google/protobuf/go_features.proto\"\xa1\x02\n" +
	"\x04Data\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.go.Data.DataTypeR\x04type\x12\x14\n" +
	"\x05large\x18\x04 \x01(\bR\x05large\x12\x1b\n" +
	"\tdek_nonce\x18\x05 \x01(\fR\bdekNonce\x12\x10\n" +
	"\x03dek\x18\x06 \x01(\fR\x03dek\x12\x1d\n" +
	"\n" +
	"data_nonce\x18\a \x01(\fR\tdataNonce\x12\x12\n" +
	"\x04data\x18\b \x01(\fR\x04data\x12\x18\n" +
	"\aversion\x18\t \x01(\x05R\aversion\"<\n" +
	"\bDataType\x12\r\n" +
	"\tLoginPass\x10\x00\x12\b\n" +
	"\x04Text\x10\x01\x12\f\n" +
	"\bBankCard\x10\x02\x12\t\n" +
	"\x05Other\x10\x03\"P\n" +
	"\tOperation\x12\x1c\n" +
	"\x04data\x18\x01 \x01(\v2\b.go.DataR\x04data\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.go.OperationTypeR\x04type\"8\n" +
	"\vPushRequest\x12)\n" +
	"\brequests\x18\x01 \x03(\v2\r.go.OperationR\brequests\"1\n" +
	"\x11OperationResponse\x12\x1c\n" +
	"\x04data\x18\x01 \x01(\v2\b.go.DataR\x04data\"9\n" +
	"\fPushResponse\x12)\n" +
	"\x04data\x18\x01 \x03(\v2\x15.go.OperationResponseR\x04data\"\r\n" +
	"\vPollRequest*3\n" +
	"\rOperationType\x12\n" +
	"\n" +
	"\x06Insert\x10\x00\x12\n" +
	"\n" +
	"\x06Update\x10\x01\x12\n" +
	"\n" +
	"\x06Delete\x10\x022\\\n" +
	"\n" +
	"StoredData\x12)\n" +
	"\x04Push\x12\x0f.go.PushRequest\x1a\x10.go.PushResponse\x12#\n" +
	"\x04Poll\x12\x0f.go.PollRequest\x1a\b.go.Data0\x01B\rZ\x03/pb\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_app_api_proto_data_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_app_api_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_app_api_proto_data_proto_goTypes = []any{
	(OperationType)(0),        // 0: go.OperationType
	(Data_DataType)(0),        // 1: go.Data.DataType
	(*Data)(nil),              // 2: go.Data
	(*Operation)(nil),         // 3: go.Operation
	(*PushRequest)(nil),       // 4: go.PushRequest
	(*OperationResponse)(nil), // 5: go.OperationResponse
	(*PushResponse)(nil),      // 6: go.PushResponse
	(*PollRequest)(nil),       // 7: go.PollRequest
}
var file_app_api_proto_data_proto_depIdxs = []int32{
	1, // 0: go.Data.type:type_name -> go.Data.DataType
	2, // 1: go.Operation.data:type_name -> go.Data
	0, // 2: go.Operation.type:type_name -> go.OperationType
	3, // 3: go.PushRequest.requests:type_name -> go.Operation
	2, // 4: go.OperationResponse.data:type_name -> go.Data
	5, // 5: go.PushResponse.data:type_name -> go.OperationResponse
	4, // 6: go.StoredData.Push:input_type -> go.PushRequest
	7, // 7: go.StoredData.Poll:input_type -> go.PollRequest
	6, // 8: go.StoredData.Push:output_type -> go.PushResponse
	2, // 9: go.StoredData.Poll:output_type -> go.Data
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_app_api_proto_data_proto_init() }
func file_app_api_proto_data_proto_init() {
	if File_app_api_proto_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_api_proto_data_proto_rawDesc), len(file_app_api_proto_data_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_api_proto_data_proto_goTypes,
		DependencyIndexes: file_app_api_proto_data_proto_depIdxs,
		EnumInfos:         file_app_api_proto_data_proto_enumTypes,
		MessageInfos:      file_app_api_proto_data_proto_msgTypes,
	}.Build()
	File_app_api_proto_data_proto = out.File
	file_app_api_proto_data_proto_goTypes = nil
	file_app_api_proto_data_proto_depIdxs = nil
}
