// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: app/api/proto/data.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data_DataType int32

const (
	Data_LoginPass Data_DataType = 0
	Data_Text      Data_DataType = 1
	Data_BankCard  Data_DataType = 2
	Data_Other     Data_DataType = 3
)

// Enum value maps for Data_DataType.
var (
	Data_DataType_name = map[int32]string{
		0: "LoginPass",
		1: "Text",
		2: "BankCard",
		3: "Other",
	}
	Data_DataType_value = map[string]int32{
		"LoginPass": 0,
		"Text":      1,
		"BankCard":  2,
		"Other":     3,
	}
)

func (x Data_DataType) Enum() *Data_DataType {
	p := new(Data_DataType)
	*p = x
	return p
}

func (x Data_DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Data_DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_api_proto_data_proto_enumTypes[0].Descriptor()
}

func (Data_DataType) Type() protoreflect.EnumType {
	return &file_app_api_proto_data_proto_enumTypes[0]
}

func (x Data_DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Data struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Type        Data_DataType          `protobuf:"varint,3,opt,name=type,enum=go.Data_DataType"`
	xxx_hidden_Large       bool                   `protobuf:"varint,4,opt,name=large"`
	xxx_hidden_DekNonce    []byte                 `protobuf:"bytes,5,opt,name=dek_nonce,json=dekNonce"`
	xxx_hidden_Dek         []byte                 `protobuf:"bytes,6,opt,name=dek"`
	xxx_hidden_DataNonce   []byte                 `protobuf:"bytes,7,opt,name=data_nonce,json=dataNonce"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,8,opt,name=data"`
	xxx_hidden_Version     int32                  `protobuf:"varint,9,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_app_api_proto_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Data) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Data) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Data) GetType() Data_DataType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Type
		}
	}
	return Data_LoginPass
}

func (x *Data) GetLarge() bool {
	if x != nil {
		return x.xxx_hidden_Large
	}
	return false
}

func (x *Data) GetDekNonce() []byte {
	if x != nil {
		return x.xxx_hidden_DekNonce
	}
	return nil
}

func (x *Data) GetDek() []byte {
	if x != nil {
		return x.xxx_hidden_Dek
	}
	return nil
}

func (x *Data) GetDataNonce() []byte {
	if x != nil {
		return x.xxx_hidden_DataNonce
	}
	return nil
}

func (x *Data) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Data) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *Data) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *Data) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *Data) SetType(v Data_DataType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *Data) SetLarge(v bool) {
	x.xxx_hidden_Large = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *Data) SetDekNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_DekNonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *Data) SetDek(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Dek = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *Data) SetDataNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_DataNonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *Data) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *Data) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *Data) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Data) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Data) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Data) HasLarge() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Data) HasDekNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Data) HasDek() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Data) HasDataNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Data) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *Data) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *Data) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Data) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *Data) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Type = Data_LoginPass
}

func (x *Data) ClearLarge() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Large = false
}

func (x *Data) ClearDekNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_DekNonce = nil
}

func (x *Data) ClearDek() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Dek = nil
}

func (x *Data) ClearDataNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_DataNonce = nil
}

func (x *Data) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Data = nil
}

func (x *Data) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Version = 0
}

type Data_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        *string
	Name      *string
	Type      *Data_DataType
	Large     *bool
	DekNonce  []byte
	Dek       []byte
	DataNonce []byte
	Data      []byte
	Version   *int32
}

func (b0 Data_builder) Build() *Data {
	m0 := &Data{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_Id = b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_Name = b.Name
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Large != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_Large = *b.Large
	}
	if b.DekNonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_DekNonce = b.DekNonce
	}
	if b.Dek != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_Dek = b.Dek
	}
	if b.DataNonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_DataNonce = b.DataNonce
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_Data = b.Data
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

type UploadRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data *Data                  `protobuf:"bytes,1,opt,name=data"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_app_api_proto_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadRequest) GetData() *Data {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *UploadRequest) SetData(v *Data) {
	x.xxx_hidden_Data = v
}

func (x *UploadRequest) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *UploadRequest) ClearData() {
	x.xxx_hidden_Data = nil
}

type UploadRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data *Data
}

func (b0 UploadRequest_builder) Build() *UploadRequest {
	m0 := &UploadRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = b.Data
	return m0
}

type BatchUploadRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data *[]*Data               `protobuf:"bytes,1,rep,name=data"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchUploadRequest) Reset() {
	*x = BatchUploadRequest{}
	mi := &file_app_api_proto_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUploadRequest) ProtoMessage() {}

func (x *BatchUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BatchUploadRequest) GetData() []*Data {
	if x != nil {
		if x.xxx_hidden_Data != nil {
			return *x.xxx_hidden_Data
		}
	}
	return nil
}

func (x *BatchUploadRequest) SetData(v []*Data) {
	x.xxx_hidden_Data = &v
}

type BatchUploadRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data []*Data
}

func (b0 BatchUploadRequest_builder) Build() *BatchUploadRequest {
	m0 := &BatchUploadRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = &b.Data
	return m0
}

type UploadResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data *Data                  `protobuf:"bytes,1,opt,name=data"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_app_api_proto_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadResponse) GetData() *Data {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *UploadResponse) SetData(v *Data) {
	x.xxx_hidden_Data = v
}

func (x *UploadResponse) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *UploadResponse) ClearData() {
	x.xxx_hidden_Data = nil
}

type UploadResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data *Data
}

func (b0 UploadResponse_builder) Build() *UploadResponse {
	m0 := &UploadResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = b.Data
	return m0
}

type BatchUploadResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data *[]*Data               `protobuf:"bytes,1,rep,name=data"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchUploadResponse) Reset() {
	*x = BatchUploadResponse{}
	mi := &file_app_api_proto_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUploadResponse) ProtoMessage() {}

func (x *BatchUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BatchUploadResponse) GetData() []*Data {
	if x != nil {
		if x.xxx_hidden_Data != nil {
			return *x.xxx_hidden_Data
		}
	}
	return nil
}

func (x *BatchUploadResponse) SetData(v []*Data) {
	x.xxx_hidden_Data = &v
}

type BatchUploadResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data []*Data
}

func (b0 BatchUploadResponse_builder) Build() *BatchUploadResponse {
	m0 := &BatchUploadResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = &b.Data
	return m0
}

var File_app_api_proto_data_proto protoreflect.FileDescriptor

const file_app_api_proto_data_proto_rawDesc = "" +
	"\n" +
	"\x18app/api/proto/data.proto\x12\x02go\x1a!google/protobuf/go_features.proto\"\xa1\x02\n" +
	"\x04Data\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.go.Data.DataTypeR\x04type\x12\x14\n" +
	"\x05large\x18\x04 \x01(\bR\x05large\x12\x1b\n" +
	"\tdek_nonce\x18\x05 \x01(\fR\bdekNonce\x12\x10\n" +
	"\x03dek\x18\x06 \x01(\fR\x03dek\x12\x1d\n" +
	"\n" +
	"data_nonce\x18\a \x01(\fR\tdataNonce\x12\x12\n" +
	"\x04data\x18\b \x01(\fR\x04data\x12\x18\n" +
	"\aversion\x18\t \x01(\x05R\aversion\"<\n" +
	"\bDataType\x12\r\n" +
	"\tLoginPass\x10\x00\x12\b\n" +
	"\x04Text\x10\x01\x12\f\n" +
	"\bBankCard\x10\x02\x12\t\n" +
	"\x05Other\x10\x03\"-\n" +
	"\rUploadRequest\x12\x1c\n" +
	"\x04data\x18\x01 \x01(\v2\b.go.DataR\x04data\"2\n" +
	"\x12BatchUploadRequest\x12\x1c\n" +
	"\x04data\x18\x01 \x03(\v2\b.go.DataR\x04data\".\n" +
	"\x0eUploadResponse\x12\x1c\n" +
	"\x04data\x18\x01 \x01(\v2\b.go.DataR\x04data\"3\n" +
	"\x13BatchUploadResponse\x12\x1c\n" +
	"\x04data\x18\x01 \x03(\v2\b.go.DataR\x04data2}\n" +
	"\n" +
	"StoredData\x12/\n" +
	"\x06Upload\x12\x11.go.UploadRequest\x1a\x12.go.UploadResponse\x12>\n" +
	"\vBatchUpload\x12\x16.go.BatchUploadRequest\x1a\x17.go.BatchUploadResponseB\rZ\x03/pb\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_app_api_proto_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_app_api_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_app_api_proto_data_proto_goTypes = []any{
	(Data_DataType)(0),          // 0: go.Data.DataType
	(*Data)(nil),                // 1: go.Data
	(*UploadRequest)(nil),       // 2: go.UploadRequest
	(*BatchUploadRequest)(nil),  // 3: go.BatchUploadRequest
	(*UploadResponse)(nil),      // 4: go.UploadResponse
	(*BatchUploadResponse)(nil), // 5: go.BatchUploadResponse
}
var file_app_api_proto_data_proto_depIdxs = []int32{
	0, // 0: go.Data.type:type_name -> go.Data.DataType
	1, // 1: go.UploadRequest.data:type_name -> go.Data
	1, // 2: go.BatchUploadRequest.data:type_name -> go.Data
	1, // 3: go.UploadResponse.data:type_name -> go.Data
	1, // 4: go.BatchUploadResponse.data:type_name -> go.Data
	2, // 5: go.StoredData.Upload:input_type -> go.UploadRequest
	3, // 6: go.StoredData.BatchUpload:input_type -> go.BatchUploadRequest
	4, // 7: go.StoredData.Upload:output_type -> go.UploadResponse
	5, // 8: go.StoredData.BatchUpload:output_type -> go.BatchUploadResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_app_api_proto_data_proto_init() }
func file_app_api_proto_data_proto_init() {
	if File_app_api_proto_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_api_proto_data_proto_rawDesc), len(file_app_api_proto_data_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_api_proto_data_proto_goTypes,
		DependencyIndexes: file_app_api_proto_data_proto_depIdxs,
		EnumInfos:         file_app_api_proto_data_proto_enumTypes,
		MessageInfos:      file_app_api_proto_data_proto_msgTypes,
	}.Build()
	File_app_api_proto_data_proto = out.File
	file_app_api_proto_data_proto_goTypes = nil
	file_app_api_proto_data_proto_depIdxs = nil
}
