// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: app/api/proto/data.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoredData_Push_FullMethodName = "/go.StoredData/Push"
	StoredData_Poll_FullMethodName = "/go.StoredData/Poll"
)

// StoredDataClient is the client API for StoredData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoredDataClient interface {
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error)
	Poll(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Data], error)
}

type storedDataClient struct {
	cc grpc.ClientConnInterface
}

func NewStoredDataClient(cc grpc.ClientConnInterface) StoredDataClient {
	return &storedDataClient{cc}
}

func (c *storedDataClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, StoredData_Push_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storedDataClient) Poll(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Data], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StoredData_ServiceDesc.Streams[0], StoredData_Poll_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PollRequest, Data]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoredData_PollClient = grpc.ServerStreamingClient[Data]

// StoredDataServer is the server API for StoredData service.
// All implementations must embed UnimplementedStoredDataServer
// for forward compatibility.
type StoredDataServer interface {
	Push(context.Context, *PushRequest) (*PushResponse, error)
	Poll(*PollRequest, grpc.ServerStreamingServer[Data]) error
	mustEmbedUnimplementedStoredDataServer()
}

// UnimplementedStoredDataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoredDataServer struct{}

func (UnimplementedStoredDataServer) Push(context.Context, *PushRequest) (*PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedStoredDataServer) Poll(*PollRequest, grpc.ServerStreamingServer[Data]) error {
	return status.Errorf(codes.Unimplemented, "method Poll not implemented")
}
func (UnimplementedStoredDataServer) mustEmbedUnimplementedStoredDataServer() {}
func (UnimplementedStoredDataServer) testEmbeddedByValue()                    {}

// UnsafeStoredDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoredDataServer will
// result in compilation errors.
type UnsafeStoredDataServer interface {
	mustEmbedUnimplementedStoredDataServer()
}

func RegisterStoredDataServer(s grpc.ServiceRegistrar, srv StoredDataServer) {
	// If the following call pancis, it indicates UnimplementedStoredDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoredData_ServiceDesc, srv)
}

func _StoredData_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoredDataServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoredData_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoredDataServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoredData_Poll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PollRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoredDataServer).Poll(m, &grpc.GenericServerStream[PollRequest, Data]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoredData_PollServer = grpc.ServerStreamingServer[Data]

// StoredData_ServiceDesc is the grpc.ServiceDesc for StoredData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoredData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go.StoredData",
	HandlerType: (*StoredDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _StoredData_Push_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Poll",
			Handler:       _StoredData_Poll_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "app/api/proto/data.proto",
}
