// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: app/api/proto/data.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoredData_Upload_FullMethodName      = "/go.StoredData/Upload"
	StoredData_BatchUpload_FullMethodName = "/go.StoredData/BatchUpload"
)

// StoredDataClient is the client API for StoredData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoredDataClient interface {
	Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error)
	BatchUpload(ctx context.Context, in *BatchUploadRequest, opts ...grpc.CallOption) (*BatchUploadResponse, error)
}

type storedDataClient struct {
	cc grpc.ClientConnInterface
}

func NewStoredDataClient(cc grpc.ClientConnInterface) StoredDataClient {
	return &storedDataClient{cc}
}

func (c *storedDataClient) Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadResponse)
	err := c.cc.Invoke(ctx, StoredData_Upload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storedDataClient) BatchUpload(ctx context.Context, in *BatchUploadRequest, opts ...grpc.CallOption) (*BatchUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUploadResponse)
	err := c.cc.Invoke(ctx, StoredData_BatchUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoredDataServer is the server API for StoredData service.
// All implementations must embed UnimplementedStoredDataServer
// for forward compatibility.
type StoredDataServer interface {
	Upload(context.Context, *UploadRequest) (*UploadResponse, error)
	BatchUpload(context.Context, *BatchUploadRequest) (*BatchUploadResponse, error)
	mustEmbedUnimplementedStoredDataServer()
}

// UnimplementedStoredDataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoredDataServer struct{}

func (UnimplementedStoredDataServer) Upload(context.Context, *UploadRequest) (*UploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedStoredDataServer) BatchUpload(context.Context, *BatchUploadRequest) (*BatchUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchUpload not implemented")
}
func (UnimplementedStoredDataServer) mustEmbedUnimplementedStoredDataServer() {}
func (UnimplementedStoredDataServer) testEmbeddedByValue()                    {}

// UnsafeStoredDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoredDataServer will
// result in compilation errors.
type UnsafeStoredDataServer interface {
	mustEmbedUnimplementedStoredDataServer()
}

func RegisterStoredDataServer(s grpc.ServiceRegistrar, srv StoredDataServer) {
	// If the following call pancis, it indicates UnimplementedStoredDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoredData_ServiceDesc, srv)
}

func _StoredData_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoredDataServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoredData_Upload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoredDataServer).Upload(ctx, req.(*UploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoredData_BatchUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoredDataServer).BatchUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoredData_BatchUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoredDataServer).BatchUpload(ctx, req.(*BatchUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StoredData_ServiceDesc is the grpc.ServiceDesc for StoredData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoredData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go.StoredData",
	HandlerType: (*StoredDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upload",
			Handler:    _StoredData_Upload_Handler,
		},
		{
			MethodName: "BatchUpload",
			Handler:    _StoredData_BatchUpload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/api/proto/data.proto",
}
